project:
  type: book
  output-dir: docs
  resources: 
    - "filters/emoji/*.png"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!Rscripts/"
    - "!_lab/"
    - "!_quiz/"

execute:
  freeze: auto

# Define book structure
book:
  title: "FIN5005 Fall 2025"
  search: true
  downloads: 
    - pdf
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - 00_environment_setup.qmd
    - part: "Basics"
      chapters:
        - 01_introduction.qmd
        - 01_Lab-1.ipynb
        - 02_Data_Visualization.qmd
        - 03_Linear_Regression.qmd
        - 04_Theoretical_Framework_LR.qmd
        - 05_Hypothesis_Testing.qmd
        - 06_Multiple_Linear_Regression.qmd
        - 07_Lab-2_dummy-variable.ipynb
        - 08_Interactions.qmd
        - 09_Logistic_Regression.qmd

filters:
  - filters/color-text.lua
  - filters/col-eqn.lua
  - filters/emoji.lua

# Output formats, styles, dependencies
format:
  html:
    include-in-header: 
      - file: themes/mathjax.html       # MathJax for LaTeX custom macro support
      - file: themes/common-header.html # load js scripts and external css (e.g., font-awesome) for all pages
    from: markdown+tex_math_single_backslash+markdown_in_html_blocks
    respect-user-color-scheme: true
    theme:
      light: [cosmo, themes/custom-light.scss]
      dark: [darkly, themes/custom-dark.scss]
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 3
  pdf:
    documentclass: scrbook
    include-in-header: 
      - file: latex/macro_book.tex
    from: markdown+tex_math_single_backslash+markdown_in_html_blocks
    keep-tex: true
    fontsize: 12pt

knitr:
  opts_chunk: 
    R.options:
      knitr.kable.NA = ''