project:
  type: website
  output-dir: docs

website:
  title: "FIN5005 Fall 2025"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Environment Setup"
        href: environment_setup.qmd
      - section: "Basics"
        contents:
          - introduction.qmd
          - Lab-1.ipynb

format:
  html:
    include-in-header: 
      - file: themes/mathjax.html
      - file: themes/common-header.html
    respect-user-color-scheme: true
    theme:
      light: [cosmo, themes/custom-light.scss]
      dark: [darkly, themes/custom-dark.scss]
    toc: true
    number-sections: true
    number-depth: 2



