project:
  type: website
  output-dir: docs

website:
  title: "2025Fall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Environment Setup"
        href: environment_setup.qmd
      - section: "Basics"
        contents:
          - introduction.qmd
          - Lab-1.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



