project:
  type: website
  output-dir: docs

website:
  title: "FIN5005 Fall 2025"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Environment Setup"
        href: 00_environment_setup.qmd
      - section: "Basics"
        contents:
          - 01_introduction.qmd
          - 01_Lab-1.ipynb
          - 02_Data_Visualization.qmd
          - 03_Linear_Regression.qmd

format:
  html:
    include-in-header: 
      - file: themes/mathjax.html       # MathJax for LaTeX custom macro support
      - file: themes/common-header.html # load js scripts and external css (e.g., font-awesome) for all pages
    respect-user-color-scheme: true
    theme:
      light: [cosmo, themes/custom-light.scss]
      dark: [darkly, themes/custom-dark.scss]
    toc: true
    number-sections: true
    number-depth: 2



