---
title: "Business Analytics (Fall 2025)"
---

## Course Overview

What Business Analytics (BA) is about?

The aim of this course is to provide students advanced knowledge, skills and competencies they can use to make data driven decisions for organizations. 

**Data-driven decision making**

- **Describe the data**: what happened
  
  Using introductory statistics to identify patterns, trends, and insights embedded in historical data. E.g., summary statistics.
- **Predictive**: what will happen
  
  Using statistical models on historical data and forecast future outcomes. E.g., regression, time series.
- Prescriptive: what should we do
  
  Using optimization, simulation, and decision analysis techniques to suggest the best course of action based on data, predictions, and constraints. 
- Autonomous: automated decision-making using Machine Learning (ML) and Artificial Intelligence (AI) techniques.


Outline of models and applications we will cover in this course:<sup>1</sup>

| **Category**     | **Topics**                               | **Applications in Business**                                                                         |
| ---------------- | ---------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| **Descriptive**  | Data Visualization, Descriptive Analysis | Asset return → **Finance**                                                                           |
| **Predictive**   | Linear regression                        | Asset return prediction → **Finance**<br>Test Score Determinants → **Sociology**                           |
|                  | Hypothesis testing                       | Test Score Determinants → **Sociology**                                                      |
|                  | Classification, logistic regression      | Asset return increasing/decreasing prediction → **Finance**<br>Employee satisfaction → **Operation** |
| **Prescriptive** | Optimization models                      | Pricing optimization → **Operation**<br>Sensitivity analysis, Scenario analysis → **Accounting**     |

<sup>[1]<sub> This is a preliminary plan. Topics and applications are subject to change as the course moves forward.</sub></sup>

--------------------------------------------------------------------------------

**Software**: R programming

R is an open-source programming language widely used for statistical computing and data analysis. It provides a rich ecosystem of packages and libraries for data manipulation, visualization, and modeling.

Why open-source stands out in the competition?

AI is the game changer here. AI significantly improves coding efficiency and productivity. You don't need to memorize every
function or syntax anymore. The current role for humans is to communicate your needs to AI, and AI will generate the code for you.

- Open-source software integrates cutting-edge AI tools, faster and more efficiently than paid software.
- By contrast, paid software is often slower to implement new features due to development cycles and licensing restrictions.

<span class="env-green"><i class="codicon codicon-debug-console" style="font-size:1.5em; vertical-align: middle;"></i> Demonstration in VS Code. </span>

By typing `# create a function taking the n-th power of a number`, AI will generate the code for you.

Here is how to use GitHub Copilot in RStudio: [RStudio User Guide: Tools, GitHub Copilot](https://docs.posit.co/ide/user/ide/guide/tools/copilot.html#using-copilot).



## Course Materials

The course materials will be self-contained. 

- **Lecture notes**: lecture notes will be provided in the course website.
- **R code**: R code will be provided in form of Lab Jupyter Notebooks.
  
  You may copy and paste the code into RStudio to run it.


If you want to learn in-depth, you can refer to the following textbooks and resources.

**Textbooks**

- Evans, J.R. (2021) *Business analytics: methods, models, and decisions*. Third edition. Harlow: Pearson.
  
  Statistics primer. Basic introduction to business analytics at the undergraduate level. 

- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning with Applications in R*. 2nd edition. Springer. [Online version](https://www.statlearning.com/)
  
  **Main textbook** for the course. It covers the fundamental concepts and methods of statistical learning, with practical applications in R.

- Huntsinger, R. (2025). *Business Analytics: Methods and Cases for Data-Driven Decisions.* Cambridge: Cambridge University Press. eTextbook available through [Cambridge University Press](https://www.cambridge.org/highereducation/books/business-analytics/49F97FC7360294F70056ADDC895C61AE#overview).
  
  Advanced methods and case studies for data-driven decision-making.
  We might use case studies from this book in the course.

**Resources:**

- [Distribution Tables](https://drive.google.com/file/d/1Iwec44x4N5AItbpFugbUOKHBIE10cMOw/view?usp=drive_link)
- [Formula Sheet](https://drive.google.com/file/d/1FhRrVo8BkmVwwQdt0Xm47j4HIBhYHCbb/view?usp=drive_link)


## Course Evaluation

**Compud Assessment**

❗️ In case of any discrepancies between the dates listed on the course website and StudentWeb, <span class="env-green">**use the dates on <u>StudentWeb</u> as the reference.**</span>

- Oppgave (home assignment): 40%
  
  Group work (1-3 students) is possible; including a case study with data analysis and visualization; a report will be submitted;
  
  Date: week 42 (preliminary date: 14.10.2025)  
  Duration: 2 weeks.

  The assignment will be released in Inspera, and you will have **two weeks** to complete it.

  More details will be provided as the course progresses.

- Eksamen (school exam): 60%
  
  Digitally in Inspera;  \
  Date: 18.11.2025 (Refer to Studentweb for the exact time)


## Study Objectives

- **Knowledge**: 
  - Familiarity with statistical methods and models used in business analytics. 
  - Focus on descriptive analytics and predictive analytics.
    Prescriptive analytics will be introduced if time allows.
  - Knowledge of data visualization techniques and tools.
- **Skills**: 
  - Ability to analyze and interpret data using statistical methods.
  - Proficiency in using R for data analysis and visualization.
  - Competence in applying business analytics techniques to real-world problems.

- **Competencies**:
  - Develop critical thinking skills to evaluate data-driven decisions.
  - Ability to communicate findings effectively through reports and presentations.

## How to Reach Me

<table border="0" cellspacing="0" cellpadding="5">
  <tr>
    <td>Instructor:</td>
    <td>Menghan Yuan</td>
  </tr>
  <tr>
    <td>Email:</td>
    <td><a href="mailto:menghan.yuan@nord.no">menghan.yuan@nord.no</a></td>
  </tr>
  <tr>
    <td>Office Hours:</td>
    <td>By appointment</td>
  </tr>
  <tr>
    <td>Office:</td>
    <td>Hovedbygning A257</td>
  </tr>
  <tr><td colspan="2">&nbsp;</td></tr>
</table>


