{
  "hash": "de9c9ad33604c5624e92f7d077d53b79",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\n---\n\nIn this session, we will use the same `CASchools` dataset from the previous session and implement a simple linear regression model to explore a question of interest: \n\n::: {.callout-important appearance=\"minimal\"}\n## Research Question\n\n<center style=\"font-size: 1.5em; font-weight: bold;\">\nDoes expenditure per students affect student performance \\\nin elementary school education?\n</center>\n:::\n\n\n## Data Preparation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages and dataset\npkgs <- c(\"tidyverse\", \"moments\", \"data.table\", \"ggsci\", \"stargazer\")\nmissing <- setdiff(pkgs, rownames(installed.packages()))\nif (length(missing) > 0) install.packages(missing)\ninvisible(lapply(pkgs, function(pkg) suppressPackageStartupMessages(library(pkg, character.only = TRUE))))\nf_name <- \"https://raw.githubusercontent.com/my1396/FIN5005-Fall2025/refs/heads/main/data/CASchools_test_score.csv\"\ncas <- read_csv(f_name,\n    col_types = cols(\n        county = col_factor(), # read as factor\n        grades = col_factor()\n    )\n)\ncas %>% as.data.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     district                          school      county grades students\n        <num>                          <char>      <fctr> <fctr>    <num>\n  1:    75119              Sunol Glen Unified     Alameda  KK-08      195\n  2:    61499            Manzanita Elementary       Butte  KK-08      240\n  3:    61549     Thermalito Union Elementary       Butte  KK-08     1550\n  4:    61457 Golden Feather Union Elementary       Butte  KK-08      243\n  5:    61523        Palermo Union Elementary       Butte  KK-08     1335\n ---                                                                     \n416:    68957          Las Lomitas Elementary   San Mateo  KK-08      984\n417:    69518            Los Altos Elementary Santa Clara  KK-08     3724\n418:    72611          Somis Union Elementary     Ventura  KK-08      441\n419:    72744               Plumas Elementary        Yuba  KK-08      101\n420:    72751            Wheatland Elementary        Yuba  KK-08     1778\n     teachers calworks   lunch computer expenditure    income   english  read\n        <num>    <num>   <num>    <num>       <num>     <num>     <num> <num>\n  1:    10.90   0.5102  2.0408       67    6384.911 22.690001  0.000000 691.6\n  2:    11.15  15.4167 47.9167      101    5099.381  9.824000  4.583333 660.5\n  3:    82.90  55.0323 76.3226      169    5501.955  8.978000 30.000002 636.3\n  4:    14.00  36.4754 77.0492       85    7101.831  8.978000  0.000000 651.9\n  5:    71.50  33.1086 78.4270      171    5235.988  9.080333 13.857677 641.8\n ---                                                                         \n416:    59.73   0.1016  3.5569      195    7290.339 28.716999  5.995935 700.9\n417:   208.48   1.0741  1.5038      721    5741.463 41.734108  4.726101 704.0\n418:    20.15   3.5635 37.1938       45    4402.832 23.733000 24.263039 648.3\n419:     5.00  11.8812 59.4059       14    4776.336  9.952000  2.970297 667.9\n420:    93.40   6.9235 47.5712      313    5993.393 12.502000  5.005624 660.5\n      math\n     <num>\n  1: 690.0\n  2: 661.9\n  3: 650.9\n  4: 643.5\n  5: 639.9\n ---      \n416: 707.7\n417: 709.5\n418: 641.7\n419: 676.5\n420: 651.0\n```\n\n\n:::\n:::\n\n\n\nVariable of interest: Test scores\n\n- `read` and `math` are average reading and math test scores for each district\n- In the [last session](#academic-performance-relationship), we show that these two variables are highly correlated (r=0.92)\n- We construct an average test score as the average of the test score for reading and the score of the math test. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute TestScore and append it to CASchools\ncas <- cas %>%\n  mutate(TestScore = (read + math) / 2)\n```\n:::\n\n\n## Descriptive Statistics\n\nRefer to the [previous session](#descriptive-analysis-and-data-visualization-with-caschools) for detailed summary statistics and visualizations.\n\nA quick preview \n\n\n```{.r .cell-code}\nv <- setdiff(names(cas), c(\"district\", \"school\", \"county\", \"grades\"))\nstargazer(as.data.frame(cas[v]), type=\"html\", digits=2)\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Statistic</td><td>N</td><td>Mean</td><td>St. Dev.</td><td>Min</td><td>Max</td></tr>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">students</td><td>420</td><td>2,628.79</td><td>3,913.10</td><td>81</td><td>27,176</td></tr>\n<tr><td style=\"text-align:left\">teachers</td><td>420</td><td>129.07</td><td>187.91</td><td>4.85</td><td>1,429.00</td></tr>\n<tr><td style=\"text-align:left\">calworks</td><td>420</td><td>13.25</td><td>11.45</td><td>0.00</td><td>78.99</td></tr>\n<tr><td style=\"text-align:left\">lunch</td><td>420</td><td>44.71</td><td>27.12</td><td>0.00</td><td>100.00</td></tr>\n<tr><td style=\"text-align:left\">computer</td><td>420</td><td>303.38</td><td>441.34</td><td>0</td><td>3,324</td></tr>\n<tr><td style=\"text-align:left\">expenditure</td><td>420</td><td>5,312.41</td><td>633.94</td><td>3,926.07</td><td>7,711.51</td></tr>\n<tr><td style=\"text-align:left\">income</td><td>420</td><td>15.32</td><td>7.23</td><td>5.34</td><td>55.33</td></tr>\n<tr><td style=\"text-align:left\">english</td><td>420</td><td>15.77</td><td>18.29</td><td>0.00</td><td>85.54</td></tr>\n<tr><td style=\"text-align:left\">read</td><td>420</td><td>654.97</td><td>20.11</td><td>604.50</td><td>704.00</td></tr>\n<tr><td style=\"text-align:left\">math</td><td>420</td><td>653.34</td><td>18.75</td><td>605.40</td><td>709.50</td></tr>\n<tr><td style=\"text-align:left\">TestScore</td><td>420</td><td>654.16</td><td>19.05</td><td>605.55</td><td>706.75</td></tr>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr></table>\n\n## Scatter Plot\n\nHypothesis: Higher spending per student leads to better test scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cas, aes(x = expenditure, y = TestScore)) +\n    geom_point(alpha = 0.6, color = \"#1976d2\") +\n    geom_smooth(method = \"lm\", color = \"#d32f2f\", se = FALSE) +\n    labs(\n        title = \"Scatter Plot of Test Scores vs. Expenditure per Student\",\n        x = \"Expenditure per Student (USD)\",\n        y = \"Average Test Score\"\n    ) +\n    theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](03_Linear_Regression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThere seems to be a positive relationship between expenditure per student and average test scores. Also note that the points are dispersed, indicating that other factors may also influence test scores. We will further explore this using multiple regression in future sessions. \n\nFor now, we will focus on a simple linear regression model with only one independent variable: expenditure per student.\n\nLet's calculate the correlation coefficient between expenditure and test scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(cas, cor.test(expenditure, TestScore))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  expenditure and TestScore\nt = 3.9841, df = 418, p-value = 7.989e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.09736861 0.28180139\nsample estimates:\n      cor \n0.1912728 \n```\n\n\n:::\n:::\n\n\n\n::: {.example #correlation}\nWhat does the correlation coefficient tell us? Is it statistically significant? Justify your answer.\n:::\n\n<button class=\"solution-btn\" onclick=\"myFunction('solution1')\">Solution</button>\n::: {#solution1 .solution-answer .env-green}\n\n- **The reported correlation coefficient** is 0.19 between expenditure and TestScore.\n  \n  This is a positive but weak correlation: higher expenditures are associated with higher test scores, but the relationship is not very strong.\n\n- **The p-value** = 7.989e-05, which is far below common significance levels (0.05, 0.01, or even 0.001).\n\n  This means we reject the null hypothesis that the true correlation is zero.\n  The result is statistically significant.\n:::\n\n\n## Simple Linear Regression\n\n### Model Specification\n\nWe will fit a simple linear regression model to examine the relationship between expenditure per student and average test scores.\n\n$$\n\\text{TestScore}_i = \\beta_0 + \\beta_1 \\times \\text{expenditure}_i + \\varepsilon_i\n$$ {#eq-linear-regression}\n\n\n@eq-linear-regression is the linear regression model with a single independent variable.\n\nWhere:\n\n:::{.callout-tip title=\"Key Components of the Linear Regression Model\"}\n\n- $\\text{TestScore}_i$ in the Left Hand Side (LHS) is the **dependent variable** (response variable). $i$ indexes different school districts.\n- $\\text{expenditure}_i$ in the Right Hand Side (RHS) is the **independent variable** (explanatory variable or regressor).\n- $\\beta_0$ and $\\beta_1$ are known as the parameters (coefficients) of the model.\n  - $\\beta_0$ is the **intercept**, representing the expected value of TestScore when expenditure is zero.\n  - $\\beta_1$ is the **slope coefficient**, representing the change in TestScore for a one dollar increase in expenditure.\n- $\\varepsilon_i$ is the error term, capturing all other factors affecting \\text{expenditure} not included in the model, e.g, teacher quality, school facilities, parental involvement, etc.\n:::\n\n\n@eq-linear-regression can be written more generally as:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + \\varepsilon_i\n$$\n\n- $\\beta_1$ is the slope coefficient, which measures the change in the dependent variable $Y$ associated with a one-unit increase in the independent variable $X.$\n- $\\beta_0$ is the intercept, which is the expected value of $Y$ when $X=0;$ it is the point at which the population regression line intersects the Y axis. \n \n📌 In some econometric applications, the intercept has a meaningful economic interpretation. In other applications, the intercept has no real-world meaning; for example, when $X$ is the expenditure per student, strictly speaking the intercept is the expected value of test scores when there is no expenditure, which might be unrealistic. \n\nWhen the real-world meaning of the intercept is nonsensical, it is best to think of it simply as the coefficient that determines the level of the regression line.\n\n### Estimating the Coefficients of the Linear Regression Model\n\nBased on the scatter plot and the correlation analysis, we expect a positive relationship between expenditure and test scores. We will use the Ordinary Least Squares (OLS) method to estimate the coefficients of the linear regression model.\n\nTo run this regression, we use the `lm()` function in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the linear regression model\nmodel <- lm(TestScore ~ expenditure, data = cas)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = TestScore ~ expenditure, data = cas)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-50.146 -14.206   0.689  13.513  50.127 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 6.236e+02  7.720e+00  80.783  < 2e-16 ***\nexpenditure 5.749e-03  1.443e-03   3.984 7.99e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.72 on 418 degrees of freedom\nMultiple R-squared:  0.03659,\tAdjusted R-squared:  0.03428 \nF-statistic: 15.87 on 1 and 418 DF,  p-value: 7.989e-05\n```\n\n\n:::\n:::\n\n\n\n### Interpretation of the output\n\n#### A. **Model Specification and Fitted Values**\n\nThe regression estimates the effect of **expenditure** (per student, in USD) on **test scores** (combined reading and math).\n\n**From Theory to Practice:**\n\nWe started with the theoretical model:\n$$\n\\text{TestScore}_i = \\beta_0 + \\beta_1 \\times \\text{expenditure}_i + \\varepsilon_i\n$$\n\nUsing OLS estimation, we obtain the <span class=\"env-green\">**fitted model**</span>:\n\n$$\n\\widehat{\\text{TestScore}} = 623.6 + 0.00575 \\times \\text{expenditure}\n$$\n\nThe hat symbol ($\\widehat{\\text{TestScore}}$) indicates these are **predicted values** based on our sample data. Notice that we no longer have the error terms ($\\varepsilon_i$) because this equation gives us the predicted values from the regression line.\n\n**Understanding Residuals:**\n\nSince our model can't perfectly predict every observation, we need to measure how far off our predictions are from reality:\n\n$$\n\\text{Residual}_i = \\text{TestScore}_i - \\widehat{\\text{TestScore}}_i\n$$\n\nResiduals represent the **difference between actual and predicted values** - essentially, they capture what our model couldn't explain. In the original theoretical model, these correspond to the error terms ($\\varepsilon_i$) that we estimated.\n\n---\n\n#### B. **Coefficients**\n\n* **Intercept (623.6):**\n  When expenditure = 0, the predicted test score is about **623.6**.\n  While not meaningful in practice (since expenditure cannot realistically be zero), it serves as the baseline of the regression line.\n\n* **Expenditure (0.00575):**\n  For every **one-dollar increase** in expenditure per student, the average test score is predicted to increase by **0.0057 points**.\n  Put differently: a **\\$1,000 increase** in expenditure is associated with a **5.75-point increase** in test scores.\n\n---\n\n#### C. **Statistical Significance**\n\nFor the slope coefficient ($\\beta_1$):\n\n* The **t-value = 3.984** and **p-value = 7.99e-05**, which is well below 0.001.\n* This indicates that expenditure has a **statistically significant positive effect** on test scores.\n\n---\n\n#### D. **Model Fit**\n\n* **R-squared = 0.0366** (about 3.7%).\n  * This means expenditure explains only a **small portion of the variation** in test scores.\n  * Many other factors (teacher quality, socio-economic background, school resources, etc.) likely play a larger role.\n\n* **F-statistic = 15.87** with a p-value of 7.99e-05.\n  * This tests the null hypothesis that all regression coefficients are equal to zero (no effect).\n  * The low p-value indicates we reject the null hypothesis, confirming that the model has some explanatory power.\n\n\n---\n\n#### E. **Residuals**\n\nThe investigation of residuals requires diagnostic test which checks the assumptions of linear regression (e.g., homoscedasticity, normality of errors).\n\n**We will cover them in future sessions**. \n\nHere we provide a brief overview.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03_Linear_Regression_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n\n* The first plot is **“Residuals vs Fitted” plot**. \n  \n  The residuals appear reasonably balanced around zero, though the spread suggests substantial unexplained variation.\n\n  The spread of residuals seems to **increase slightly with fitted values**, indicating potential heteroscedasticity (non-constant variance of errors). This suggests that the assumption of homoscedasticity may be violated, which could affect the reliability of our coefficient estimates and standard errors.\n\n* The second plot is the **normal Q-Q plot**, which assesses whether the residuals are normally distributed. \n\n  * The points generally follow the reference line, suggesting that the residuals are approximately normally distributed, although there shows thin tails.\n  \n  * This indicates that there are few extreme residuals. The model predictions don't have large outliers.\n\n**From the summary output:**\n\n* The **residual standard error = 18.72**, which is the average size of prediction errors (in test score points).\n\n\n---\n\n✅ **Summary Interpretation:**\n\nThe regression analysis shows a **statistically significant positive relationship** between school expenditure and test scores. On average, an additional \\\\$1,000 in per-student expenditure is associated with an increase of about **5.75 points** in test scores. However, the **explanatory power of the model is low (R² ≈ 3.7%)**, indicating that expenditure alone explains only a small fraction of the variation in test scores. This suggests that while spending matters, many other factors also influence student performance.\n\nTo gain a more comprehensive understanding of the factors affecting student achievement, future analyses should employ **multiple regression models** that incorporate additional explanatory variables such as student demographics, teacher qualifications, and school characteristics. We will cover multiple regression in subsequent sessions.\n\n\n## Report by Stargazer\n\n`stargazer` produces well-formatted regression tables that can be easily included in reports or publications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(model, type = \"text\", digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===============================================\n                        Dependent variable:    \n                    ---------------------------\n                             TestScore         \n-----------------------------------------------\nexpenditure                   0.01***          \n                              (0.001)          \n                                               \nConstant                     623.62***         \n                              (7.72)           \n                                               \n-----------------------------------------------\nObservations                    420            \nR2                             0.04            \nAdjusted R2                    0.03            \nResidual Std. Error      18.72 (df = 418)      \nF Statistic           15.87*** (df = 1; 418)   \n===============================================\nNote:               *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n--------------------------------------------------------------------------------\n\n<h3>References</h3>\n\n- [Introduction to Econometrics with R](https://www.econometrics-with-r.org/4.2-estimating-the-coefficients-of-the-linear-regression-model.html)",
    "supporting": [
      "03_Linear_Regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}