{
  "hash": "847ef0e2fb995dd2521e3a9bf0738795",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Theoretical Framework of Linear Regression\"\n---\n\nIn this section, we will discuss the theoretical framework of linear regression, including the assumptions underlying the linear regression model and essential hypothesis tests.\n\nQ: Why the assumptions matter?\n\nA: In short, violation of the assumptions may lead to biased or inefficient estimates, incorrect inferences, and unreliable predictions.\n\n--------------------------------------------------------------------------------\n\n## Assumptions of Linear Regression\n\nQ: What are the assumptions of linear regression?\n\nA: The **Gauss-Markov Assumptions** ensure that the Ordinary Least Squares (OLS) estimator is the Best Linear Unbiased Estimator (BLUE). \n\n1. **Linearity**: The relationship between the independent variable(s) and the dependent variable is linear in parameters.\n2. **No perfect multicollinearity**: The independent variables are NOT <span class=\"env-orange\">perfectly correlated.</span>\n3. **Error has zero conditional mean**\n4. **Error is homoskedastic**\n   - Homoscedasticity: The variance of the error term is constant across all levels of the independent variable(s).\n   \n   <span style=\"color: #888888;\">In time series settings (we won't cover in this course), we also assume:</span>\n   \n   - <span style=\"color: #888888;\">No autocorrelation: The error terms are not correlated with each other.</span>\n   \n5. **Residuals are normally distributed**\n   \n   This assumption is useful for conducting hypothesis tests and constructing confidence intervals. \n\n## Regression Framework\n\nMultiple linear regression models is defined as \n\n$$\nY_i = \\beta_0 + \\beta_1 X_{i1} + \\beta_2 X_{i2} + ... + \\beta_k X_{ik} + \\varepsilon_i\n$$\n\n\nwhere $i$ indexes the observations, $Y_i$ is the dependent variable, and $X_{ij}$ represents the $j$-th independent variable for observation $i$, with $j = 1, \\ldots, k$ and $k$ denoting the total number of independent variables. The coefficients $\\beta_j$ are to be estimated, and $\\varepsilon_i$ is the error term.\n\n**OLS estimator $\\hat{\\beta}^{OLS}$ minimizes the sum of squared residuals (SSR)**:\n\n$$\n\\hat{\\beta}^{OLS} = \\arg\\min_{\\beta} \\sum_{i=1}^{n} e_i^2 \n$$\n\nwhere $e_i = Y_i - \\hat{Y}_i$ is the residual for observation $i$.\n\n$\\hat{Y}_i$ is the predicted value of $Y_i$ given the estimated coefficients.\n\n$$\n\\hat{\\beta}^{OLS} = \\arg\\min_{\\beta} \\sum_{i=1}^{n} (Y_i - \\beta_0 - \\sum_{j=1}^{k} \\beta_j X_{ij})^2\n$$\n\n\n**Properties of OLS estimator:**\n\n- **Unbiasedness**: $E[\\hat{\\beta}^{OLS}] = \\beta$ (if Gauss-Markov assumptions hold)\n- **Efficiency**: Among all linear unbiased estimators, OLS has the smallest variance\n- **Consistency**: As sample size $n \\to \\infty$, $\\hat{\\beta}^{OLS} \\to \\beta$ in probability\n\n## Measure of Fit\n\nWe often use $R^2$ to measure the goodness of fit of a regression model. \n\n- It represents the proportion of variance in the dependent variable that is predictable by the regression model.\n\n$R^2$ is defined as:\n\n$$\nR^2 = 1 - \\frac{SSR}{SST} = \\frac{SST - SSR}{SST} = \\frac{SSE}{SST}\n$$\n\nwhere\n\n- $SSR = \\sum_{i=1}^{n} (Y_i - \\hat{Y}_i)^2 = \\sum_{i=1}^{n} e_i^2$ is the sum of squared residuals (unexplained variation)\n- $SST = \\sum_{i=1}^{n} (Y_i - \\bar{Y})^2$ is the total sum of squares (total variation)\n- $SSE = \\sum_{i=1}^{n} (\\hat{Y}_i - \\bar{Y})^2$ is the explained sum of squares (explained variation)\n- $\\bar{Y}= \\frac{1}{n}\\sum_{i=1}^n Y_i$ is the mean of the dependent variable\n\nNote that adding variables always increases $R^2$, even if the new variables are not statistically significant. To address this, we use the **adjusted $R^2$**.\n\nIn a regression model with multiple explanatory variables, we often use **adjusted** $R^2$ that adjusts the number of explanatory variables.\n\n\n## Hypothesis Testing in Regression\n\nWe have been using t-statistics and p-values to for testing hypotheses such as whether a correlation coefficient is significantly different from zero or if a regression coefficient is significantly different from zero.\n\nIn the following section, we will introduce the procedure of hypothesis testing formally. \n\n:::{.callout-important title=\"Study objectives for hypothesis testing\"}\nThe goal is be able to conduct hypothesis test manually given necessary information.\n\nFor example, in case of testing if a regression coefficient is significantly different from zero, you should be able to \n\n::: {.step-list style=\"font-size: 1.2em;\"}\n1. Establish null and alternative hypotheses.\n2. Calculate the t-statistic given the coefficient estimate, standard error.\n3. Find the critical value of your test statistic given the significance level, 5% is commonly used.\n   \n   You need to be familiar with the distribution table to find the critical value. The tables can be found in the formula sheet on Canvas under the \"Past Exam\" module.\n4. Decision rule. \n   \n   Compare the t-stat with the critical value to make decision on rejecting or not rejecting the null hypothesis.\n5. Interpret the result in context. What it means in reality?\n:::\n\n:::\n\n### t-test for Single Coefficient\n\nUsing the simple linear regression model of California School Test Scores in the previous session as an example, test whether expenditure has a significant effect on test scores at the 5% significance level.\n\n```\nCall:\nlm(formula = TestScore ~ expenditure, data = cas)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-50.146 -14.206   0.689  13.513  50.127 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 6.236e+02  7.720e+00  80.783  < 2e-16 ***\nexpenditure 5.749e-03  1.443e-03   3.984 7.99e-05 ***\n---\nSignif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1\n\nResidual standard error: 18.72 on 418 degrees of freedom\nMultiple R-squared:  0.03659,   Adjusted R-squared:  0.03428 \nF-statistic: 15.87 on 1 and 418 DF,  p-value: 7.989e-05\n```\n\nHere is the hypothesis test step by step for the expenditure coefficient in the simple linear regression of California school test scores.\n\n::: {.step-list}\n1. Hypotheses\n\n   * $H_0:\\ \\beta_{\\text{exp}} = 0$  (expenditure has no effect on test scores)\n   * $H_1:\\ \\beta_{\\text{exp}} \\neq 0$  (two-sided)\n\n2. Test statistic\n   \n   Estimate $= 0.005749$, standard error $= 0.001443$.\n\n   $$\n   t=\\frac{\\hat\\beta}{\\text{SE}}=\\frac{0.005749}{0.001443}=3.984\n   $$\n\n   The **degrees of freedom (df)** $= n - k - 1,$ where $n=420$ (number of observations) and $k=1$ (number of predictors), so $df=420-1-1=418$.\n\n3. Critical value at 5%\n   \n   Two-sided $t_{0.975,418}\\approx 1.96$.\n\n   :::{.callout-tip title=\"Finding critical value\"}\n   Notice that when df is large, the critical value approaches that of the standard normal distribution, $z_{0.975}=1.96$.\n\n   The rule-of-thumb is that when $df > 30$, you can use the standard normal critical values.\n   :::\n\n4. Decision rule\n   \n   - Reject $H_0$ if $|t|>1.96$. \n   - Fail to reject $H_0$ if $|t|\\leq 1.96$.\n   \n   Since $3.984>1.97$, reject $H_0$.\n\n5. Interpretation in context\n   \n   Expenditure has a statistically significant positive association with test scores at the 5% level. The point estimate implies that a \\\\$1,000 increase in per-student expenditure is associated with about $0.005749\\times 1000=5.75$ points higher test scores. \n:::\n\n\n### Confidence Interval for Single Coefficient\n\nA 95 percent confidence interval for the slope is given by\n\n$$\n\\left(\\hat{\\beta}-C_{\\alpha/2}\\times SE(\\hat{\\beta}),\\; \\hat{\\beta}+C_{\\alpha/2}\\times SE(\\hat{\\beta})\\right)\n$$\n\nwhere $C_{\\alpha/2}$ is the critical value for a two-sided test at significance level $\\alpha$.\n\nFor the expenditure coefficient in the simple linear regression of California school test scores, $\\hat{\\beta}=0.005749$, $SE(\\hat{\\beta})=0.001443$, and $C_{0.025}=1.96$.\n\n\n\nA 95% confidence interval is therefore\n\n$$\n0.005749 \\pm 1.97\\times 0.001443 \\approx [0.0029,\\ 0.0086],\n$$\n\nwhich corresponds to roughly 2.9 to 8.6 points per \\$1,000. \n\nThe effect is statistically significant but modest in size, and the low $R^2$ indicates that many other factors also influence test scores.\n\n### F-test for Significance of the Overall Regression\n\nF-test is also known as the one-way analysis of variance (ANOVA) test. It tests whether the regression model as a whole is statistically significant.\n\n[To be finished...]\n\n\n\n### Homoskedasticity \n\nHomoskedasticity assumption requires constant variance of the error term across all levels of the independent variable(s).\n\n$$\n\\var(\\varepsilon_i | X) = \\sigma^2\n$$\n\nWhen the assumption is violated, we have heteroskedasticity:\n\n$$\n\\var(\\varepsilon_i | X) = \\sigma^2_i\n$$\n\nthat is, the variance of the error term varies with the level of the independent variable(s).\n\nIf the error has heteroskedasticity, the standard error under homoskedasticity assumption will be underestimated, leading to invalid t statistics, affecting hypothesis tests and confidence intervals.\n\nA quick fix is to use heteroskedasticity-robust standard errors, which are valid even when the homoskedasticity assumption is violated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(sandwich) # for robust standard errors\nlibrary(lmtest)   # for coeftest()\nf_name <- \"https://raw.githubusercontent.com/my1396/FIN5005-Fall2025/refs/heads/main/data/CASchools_test_score.csv\"\ncas <- read_csv(f_name,\n    col_types = cols(\n        county = col_factor(), # read as factor\n        grades = col_factor()\n    )\n)\ncas <- cas %>%\n    mutate(TestScore = (read + math) / 2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(TestScore ~ expenditure, data = cas)\n# heteroskedasticity-robust standard errors\ncoeftest(model, vcov = vcovHC(model, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n              Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 6.2362e+02 8.4664e+00  73.657 < 2.2e-16 ***\nexpenditure 5.7488e-03 1.6203e-03   3.548 0.0004322 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n**Under the heteroskedasticity-robust standard errors:**\n\n- no effects on the coefficient estimates\n- the Std. Error is slightly larger (0.001620 vs. 0.001443). The coefficient remains statistically significant at the 5% level.\n\n**Interpretation**\n\nThe heteroskedasticity-robust results suggest that the OLS standard errors may have been too optimistic (underestimated variability). While the statistical significance of the expenditure effect is slightly reduced, it remains highly significant, indicating a robust positive relationship between expenditure and test scores.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}