{
  "hash": "efbd4912c8b2233d5280d35ad727207e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Interactions\"\n---\n\nFor the course of this section, you will work with `Boston`, the Boston Housing data set which contains 506 observations on housing values in suburbs of Boston.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages and dataset\npkgs <- c(\"tidyverse\", \"MASS\", \"data.table\", \"stargazer\")\nmissing <- setdiff(pkgs, rownames(installed.packages()))\nif (length(missing) > 0) install.packages(missing)\ninvisible(lapply(pkgs, function(pkg) suppressPackageStartupMessages(library(pkg, character.only = TRUE))))\ndata(Boston) # Boston housing data\n```\n:::\n\n\nUse `?Boston` to see the description of the dataset.\n\nHere are some variables in the dataset which we are going to use in this session.\n\n| Variables | Definitions                                                  |\n| --------- | ------------------------------------------------------------ |\n| `medv`    | median value of owner-occupied homes in \\$1000s.             |\n| `lstat`   | the percentage of individuals with low socioeconomic status  |\n| `indus`   | proportion of non-retail business acres per town.            |\n| `age`     | proportion of owner-occupied units built prior to 1940.      |\n| `crim`    | per capita crime rate by town.                               |\n| `chas`    | A dummy variable. Takes the value 1 if the Charles River (a short river in the proximity of Boston) passes through the suburb and is 0 otherwise. |\n\nConsider the following regression model\n\n$$\nmedv_i = \\beta_0 + \\beta_1\\, chas_i + \\beta_2\\, old_i + \\beta_3\\, (chas_i \\times old_i) + u_i\n$$\n\nwhere $chas_i$ and $old_i$ are dummy variables defined as follows:\n\n$$\n\\begin{aligned}\nchas_i &= \\begin{cases}\n1 & \\text{if the suburb is next to the Charles River} \\\\\n0 & \\text{otherwise}\n\\end{cases} \\\\\nold_i &= \\begin{cases}\n1 & \\text{if } age_i \\ge 95 \\\\\n0 & \\text{otherwise}\n\\end{cases}\n\\end{aligned}\n$$\n\nwhere $agi_i$ being the proportion of owner-occupied units built prior to 1940.\n\n**Instructions:**\n\n- Generate and append the binary variable $old$ to the dataset Boston.\n- Conduct the regression stated above and assign the result to `mod_bb`.\n- Obtain a robust coefficient summary of the model. How do you interpret the results?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBoston <- Boston %>%\n  mutate(old = ifelse(age >= 95, 1, 0))\nmod_bb <- lm(medv ~ chas * old, data = Boston)\nsummary(mod_bb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = medv ~ chas * old, data = Boston)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-17.771  -4.765  -1.683   2.776  33.433 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  23.6989     0.4503  52.624  < 2e-16 ***\nchas          4.0582     1.6872   2.405   0.0165 *  \nold          -7.1319     0.9493  -7.513 2.67e-13 ***\nchas:old     10.5462     3.7577   2.807   0.0052 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.604 on 502 degrees of freedom\nMultiple R-squared:  0.1301,\tAdjusted R-squared:  0.1249 \nF-statistic: 25.02 on 3 and 502 DF,  p-value: 4.244e-15\n```\n\n\n:::\n:::\n\n\nThe estimated regression model is given by\n\n$$\n\\widehat{medv}_i = 23.70 + 4.06\\, chas_i - 7.13\\, old_i - 10.55\\, (chas_i \\times old_i)\n$$\n\n<span class=\"env-green\">**Interpretation of the coefficients**</span>\n\nWe start with listing all possible combinations of the binary variables $chas_i$ and $old_i$.\n\n| Scenario | $chas_i$ | $old_i$ | Interpretation                                      |\n| --- | -------- | ------- | --------------------------------------------------- |\n| 1 | 0        | 0       | Suburb not next to Charles River and new |\n| 2 | 0        | 1       | Suburb not next to Charles River and old |\n| 3 | 1        | 0       | Suburb next to Charles River and new     |\n| 4 | 1        | 1       | Suburb next to Charles River and old     |\n\n\nBased on the estimated regression model, we can compute the expected value of `medv` for each of the four groups.\n\n| Scenario | $chas_i$ | $old_i$ | $chas_i \\times old_i$ | Expected value of `medv`                                                                 |\n|:--------:|:--------:|:-------:|:---------------------:|:-----------------------------------------------------------------------------------------|\n|    1     |    0     |    0    |          0            | $\\hat{\\beta}_0 = 23.70$                                                                  |\n|    2     |    0     |    1    |          0            | $\\hat{\\beta}_0 + \\hat{\\beta}_2 = 23.70 - 7.13 = 16.57$                                   |\n|    3     |    1     |    0    |          0            | $\\hat{\\beta}_0 + \\hat{\\beta}_1 = 23.70 + 4.06 = 27.76$                                   |\n|    4     |    1     |    1    |          1            | $\\hat{\\beta}_0 + \\hat{\\beta}_1 + \\hat{\\beta}_2 + \\hat{\\beta}_3 = 23.70 + 4.06 - 7.13 - 10.55 = 10.08$ |\n\n\nFrom the table above, we can interpret the coefficients as follows:\n\n- $\\hat{\\beta}_0 = 23.70$ is the expected value of `medv` for suburbs that are not next to the Charles River and are new (i.e., `old = 0`).\n\n- Comparing scenario 2 with 1: $\\hat{\\beta}_2 = -7.13$ is the difference in expected value of `medv` between new and old suburbs that are **NOT next to the Charles River**. \n  \n  In other words, old suburbs that are not next to the Charles River have an expected `medv` that is 7.13 lower than new suburbs that are **NOT next to the Charles River**.\n\n- Comparing scenario 3 with 1: $\\hat{\\beta}_1 = 4.06$ is the difference in expected value of `medv` between suburbs that are next to the Charles River and those that are not, among **new** suburbs (i.e., `old = 0`). \n  \n  In other words, **new** suburbs that are next to the Charles River have an expected `medv` that is 4.06 higher than new suburbs that are not next to the Charles River.\n\n- $\\hat{\\beta}_3 = -10.55$ has two interpretations:\n  - If we compare scenario 4 with scenario 2, the difference in expected value of `medv` is given by $\\hat{\\beta}_1 + \\hat{\\beta}_3 = 4.06 - 10.55 = -6.49.$ \n    \n    This means that **old** suburbs that are next to the Charles River have an expected `medv` that is 6.49 lower than **old** suburbs that are not next to the Charles River. \n\n    → $\\beta_3$ can be interpreted as the difference in the effect of being next to the Charles River between old and new suburbs.\n\n  - If we compare scenario 4 with scenario 3, the difference in expected value of `medv` is given by $\\hat{\\beta}_2 + \\hat{\\beta}_3 = -7.13 - 10.55 = -17.68.$\n    \n    This means that old suburbs that are **next to the Charles River** have an expected `medv` that is 17.68 lower than new suburbs that are **next to the Charles River**.\n\n    → $\\beta_3$ can be interpreted as the difference in the effect of being old between suburbs that are next to the Charles River and those that are not.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}