<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression with a Binary Dependent Variable – FIN5005 Fall 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-8ef56b68f8fa1e9d2ba328e99e439f80.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b1eab047c83979204f5fc89f48c6bdb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-f904b3a17f9ba91b23ca1e8d6d4821c4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-b1eab047c83979204f5fc89f48c6bdb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- This is what works with Quarto and MathJax 3+ -->
<script>
  MathJax = {
    loader: { 
      load: ['[tex]/colorV2'] 
    },
    tex: {
      packages: { '[+]': ['color'] }, // load the colorV2 package
      inlineMath: [   // start/end delimiter pairs for in-line math
        ['$', '$'],
        ['\\(', '\\)']
      ],
      displayMath: [  // start/end delimiter pairs for display math
        ['$$', '$$'],
        ['\\[', '\\]']
      ],
      processEscapes: true, // use \$ to produce a literal dollar sign
      tags: 'ams',  // should be 'ams', 'none', or 'all'
      macros: {  //define TeX macros
        bold: ["{\\boldsymbol #1}", 1],  // use \bold as a shorthand
        indep: "{\\perp \\!\\!\\! \\perp}",
        vect: ["\\mathbf{#1}", 1],
        mat: ["\\mathbf{#1}", 1],

        bA: "\\boldsymbol{A}",
        bB: "\\boldsymbol{B}",
        bC: "\\boldsymbol{C}",
        bD: "\\boldsymbol{D}",
        bE: "\\boldsymbol{E}",
        bF: "\\boldsymbol{F}",
        bG: "\\boldsymbol{G}",
        bH: "\\boldsymbol{H}",
        bI: "\\boldsymbol{I}",
        bJ: "\\boldsymbol{J}",
        bK: "\\boldsymbol{K}",
        bL: "\\boldsymbol{L}",
        bM: "\\boldsymbol{M}",
        bN: "\\boldsymbol{N}",
        bP: "\\boldsymbol{P}",
        bQ: "\\boldsymbol{Q}",
        bR: "\\boldsymbol{R}",
        bS: "\\boldsymbol{S}",
        bT: "\\boldsymbol{T}",
        bU: "\\boldsymbol{U}",
        bV: "\\boldsymbol{V}",
        bW: "\\boldsymbol{W}",
        bX: "\\boldsymbol{X}",
        bY: "\\boldsymbol{Y}",
        bZ: "\\boldsymbol{Z}",
        ba: "\\boldsymbol{a}",
        bb: "\\boldsymbol{b}",
        bc: "\\boldsymbol{c}",
        bd: "\\boldsymbol{d}",
        be: "\\boldsymbol{e}",
        bg: "\\boldsymbol{g}",
        bh: "\\boldsymbol{h}",
        bi: "\\boldsymbol{i}",
        bm: "\\boldsymbol{m}",
        bp: "\\boldsymbol{p}",
        bq: "\\boldsymbol{q}",
        br: "\\boldsymbol{r}",
        bs: "\\boldsymbol{s}",
        bt: "\\boldsymbol{t}",
        bu: "\\boldsymbol{u}",
        bv: "\\boldsymbol{v}",
        bw: "\\boldsymbol{w}",
        bx: "\\boldsymbol{x}",
        by: "\\boldsymbol{y}",
        bz: "\\boldsymbol{z}",

        Acal: "\\mathcal{A}",
        Bcal: "\\mathcal{B}",
        Ccal: "\\mathcal{C}",
        Dcal: "\\mathcal{D}",
        Ecal: "\\mathcal{E}",
        Fcal: "\\mathcal{F}",
        Gcal: "\\mathcal{G}",
        Hcal: "\\mathcal{H}",
        Ical: "\\mathcal{I}",
        Jcal: "\\mathcal{J}",
        Kcal: "\\mathcal{K}",
        Lcal: "\\mathcal{L}",
        Mcal: "\\mathcal{M}",
        Ncal: "\\mathcal{N}",
        Ocal: "\\mathcal{O}",
        Pcal: "\\mathcal{P}",
        Qcal: "\\mathcal{Q}",
        Rcal: "\\mathcal{R}",
        Scal: "\\mathcal{S}",
        Tcal: "\\mathcal{T}",
        Ucal: "\\mathcal{U}",
        Vcal: "\\mathcal{V}",
        Wcal: "\\mathcal{W}",
        Xcal: "\\mathcal{X}",
        Ycal: "\\mathcal{Y}",
        Zcal: "\\mathcal{Z}",

        A: "\\mathbb{A}",
        B: "\\mathbb{B}",
        C: "\\mathbb{C}",
        D: "\\mathbb{D}",
        E: "\\mathbb{E}",
        F: "\\mathbb{F}",
        G: "\\mathbb{G}",
        H: "\\mathbb{H}",
        I: "\\mathbb{I}",
        J: "\\mathbb{J}",
        K: "\\mathbb{K}",
        L: "\\mathbb{L}",
        M: "\\mathbb{M}",
        N: "\\mathbb{N}",
        O: "\\mathbb{O}",
        P: "\\mathbb{P}",
        Q: "\\mathbb{Q}",
        R: "\\mathbb{R}",
        S: "\\mathbb{S}",
        T: "\\mathbb{T}",
        U: "\\mathbb{U}",
        V: "\\mathbb{V}",
        W: "\\mathbb{W}",
        X: "\\mathbb{X}",
        Y: "\\mathbb{Y}",
        Z: "\\mathbb{Z}",

        bAlpha: "\\boldsymbol{\\Alpha}",
        bBeta: "\\boldsymbol{\\beta}",
        bDelta: "\\boldsymbol{\\delta}",
        bEta: "\\boldsymbol{\\eta}",
        bGamma: "\\boldsymbol{\\Gamma}",
        bLambda: "\\boldsymbol{\\Lambda}",
        bOmega: "\\boldsymbol{\\Omega}",
        bPhi: "\\boldsymbol{\\Phi}",
        bPi: "\\boldsymbol{\\Pi}",
        bPsi: "\\boldsymbol{\\Psi}",
        bSigma: "\\boldsymbol{\\Sigma}",
        bTau: "\\boldsymbol{\\tau}",
        bXi: "\\boldsymbol{\\Xi}",
        bLambda: "\\boldsymbol{\\Lambda}",

        balpha: "\\boldsymbol{\\alpha}",
        bbeta: "\\boldsymbol{\\beta}",
        bepsilon: "\\boldsymbol{\\epsilon}",
        bvarepsilon: "\\boldsymbol{\\varepsilon}",
        bdelta: "\\boldsymbol{\\delta}",
        blambda: "\\boldsymbol{\\lambda}",
        bmu: "\\boldsymbol{\\mu}",
        bphi: "\\boldsymbol{\\phi}",
        bpi: "\\boldsymbol{\\pi}",
        bpsi: "\\boldsymbol{\\psi}",
        brho: "\\boldsymbol{\\rho}",
        bsigma: "\\boldsymbol{\\sigma}",
        btau: "\\boldsymbol{\\tau}",
        bxi: "\\boldsymbol{\\xi}",
        bEta: "\\boldsymbol{\\eta}",
        bPhi: "\\boldsymbol{\\Phi}",
        bPi: "\\boldsymbol{\\Pi}",
        bPsi: "\\boldsymbol{\\Psi}",
        bXi: "\\boldsymbol{\\Xi}",
        blambda: "\\boldsymbol{\\lambda}",
        bmu: "\\boldsymbol{\\mu}",
        bphi: "\\boldsymbol{\\phi}",
        bpi: "\\boldsymbol{\\pi}",
        bpsi: "\\boldsymbol{\\psi}",
        brho: "\\boldsymbol{\\rho}",
        bsigma: "\\boldsymbol{\\sigma}",

        curl: ["\\left\\lbrace#1\\right\\rbrace", 1],
        floor: ["\\left\\lfloor#1\\right\\rfloor", 1],
        ceil: ["\\left\\lceil#1\\right\\rceil", 1],
        abs: ["\\left\\lvert#1\\right\\rvert", 1],
        norm: ["\\left\\lVert#1\\right\\rVert", 1],

        independent: "\\mathrel{\\perp\\!\\!\\perp}",

        var: "\\mathrm{Var}",
        cov: "\\mathrm{Cov}",
        cor: "\\mathrm{Corr}",
        diag: "\\mathrm{diag}",
        rank: "\\mathrm{rank}",
        vecc: "\\mathrm{vec}",
        
        // define colors
        red: ["{\\color[RGB]{246, 87, 55}{#1}}", 1],
        green: ["{\\color[RGB]{0, 204, 102}{#1}}", 1], // #00CC66
      }
    }
  };
</script>
<!-- ===================== Icon Library ====================== -->
<!-- load Font Awesome 6 icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css">
<!-- Load MS codicon library -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@vscode/codicons@latest/dist/codicon.css">

<!-- ============== js for show/hide solutions ================ -->
<script language="JavaScript" src="themes/my_jxscript.js"></script>



  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">FIN5005 Fall 2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_introduction.html">Basics</a></li><li class="breadcrumb-item"><a href="./09_Logistic_Regression.html">Regression with a Binary Dependent Variable</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_environment_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Environment Setup</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability and Data in Business Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Lab-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 1: Probability &amp; Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Data_Visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Linear_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Theoretical_Framework_LR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Theoretical Framework of Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Testing and Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Multiple_Linear_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Lab-2_dummy-variable.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 2: Regression with Dummy Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions of Binary Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Logistic_Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Regression with a Binary Dependent Variable</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-binary-dependent-variables-require-special-treatment" id="toc-why-binary-dependent-variables-require-special-treatment" class="nav-link active" data-scroll-target="#why-binary-dependent-variables-require-special-treatment"><span class="header-section-number">1</span> Why Binary Dependent Variables Require Special Treatment</a>
  <ul>
  <li><a href="#why-linear-regression-fails" id="toc-why-linear-regression-fails" class="nav-link" data-scroll-target="#why-linear-regression-fails"><span class="header-section-number">1.1</span> Why Linear Regression Fails</a></li>
  <li><a href="#the-solution-logit-and-probit-models" id="toc-the-solution-logit-and-probit-models" class="nav-link" data-scroll-target="#the-solution-logit-and-probit-models"><span class="header-section-number">1.2</span> The Solution: Logit and Probit Models</a></li>
  </ul></li>
  <li><a href="#the-hmda-dataset-mortgage-lending-discrimination" id="toc-the-hmda-dataset-mortgage-lending-discrimination" class="nav-link" data-scroll-target="#the-hmda-dataset-mortgage-lending-discrimination"><span class="header-section-number">2</span> The HMDA Dataset: Mortgage Lending Discrimination</a>
  <ul>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data"><span class="header-section-number">2.1</span> Load the Data</a></li>
  <li><a href="#variable-definitions" id="toc-variable-definitions" class="nav-link" data-scroll-target="#variable-definitions"><span class="header-section-number">2.2</span> Variable Definitions</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">2.3</span> Data Exploration</a>
  <ul class="collapse">
  <li><a href="#frequency-tables-and-contingency-tables" id="toc-frequency-tables-and-contingency-tables" class="nav-link" data-scroll-target="#frequency-tables-and-contingency-tables">Frequency Tables and Contingency Tables</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a></li>
  </ul></li>
  <li><a href="#visualizing-the-contingency-table" id="toc-visualizing-the-contingency-table" class="nav-link" data-scroll-target="#visualizing-the-contingency-table"><span class="header-section-number">2.4</span> Visualizing the Contingency Table</a>
  <ul class="collapse">
  <li><a href="#mosaic-plot" id="toc-mosaic-plot" class="nav-link" data-scroll-target="#mosaic-plot">Mosaic Plot</a></li>
  </ul></li>
  <li><a href="#measures-of-risk-and-association-for-binary-outcomes" id="toc-measures-of-risk-and-association-for-binary-outcomes" class="nav-link" data-scroll-target="#measures-of-risk-and-association-for-binary-outcomes"><span class="header-section-number">2.5</span> Measures of Risk and Association for Binary Outcomes</a></li>
  </ul></li>
  <li><a href="#model-specification-the-boston-mortgage-example" id="toc-model-specification-the-boston-mortgage-example" class="nav-link" data-scroll-target="#model-specification-the-boston-mortgage-example"><span class="header-section-number">3</span> Model Specification: The Boston Mortgage Example</a>
  <ul>
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data"><span class="header-section-number">3.1</span> Preparing the Data</a></li>
  <li><a href="#model-1-linear-probability-model" id="toc-model-1-linear-probability-model" class="nav-link" data-scroll-target="#model-1-linear-probability-model"><span class="header-section-number">3.2</span> Model 1: Linear Probability Model</a></li>
  <li><a href="#model-2-logit-regression-with-a-single-predictor" id="toc-model-2-logit-regression-with-a-single-predictor" class="nav-link" data-scroll-target="#model-2-logit-regression-with-a-single-predictor"><span class="header-section-number">3.3</span> Model 2: Logit Regression with a single predictor</a></li>
  <li><a href="#model-3-linear-probability-model-with-multiple-predictors" id="toc-model-3-linear-probability-model-with-multiple-predictors" class="nav-link" data-scroll-target="#model-3-linear-probability-model-with-multiple-predictors"><span class="header-section-number">3.4</span> Model 3: Linear Probability Model with Multiple Predictors</a></li>
  <li><a href="#model-4-logit-model-with-multiple-predictors" id="toc-model-4-logit-model-with-multiple-predictors" class="nav-link" data-scroll-target="#model-4-logit-model-with-multiple-predictors"><span class="header-section-number">3.5</span> Model 4: Logit Model with Multiple Predictors</a></li>
  <li><a href="#model-5-probit-model" id="toc-model-5-probit-model" class="nav-link" data-scroll-target="#model-5-probit-model"><span class="header-section-number">3.6</span> Model 5: Probit Model</a></li>
  <li><a href="#comparison-logit-and-probit" id="toc-comparison-logit-and-probit" class="nav-link" data-scroll-target="#comparison-logit-and-probit"><span class="header-section-number">3.7</span> Comparison: Logit, and Probit</a></li>
  <li><a href="#predicted-probabilities" id="toc-predicted-probabilities" class="nav-link" data-scroll-target="#predicted-probabilities"><span class="header-section-number">3.8</span> Predicted Probabilities</a></li>
  </ul></li>
  <li><a href="#summary-logit-vs.-probit-vs.-lpm" id="toc-summary-logit-vs.-probit-vs.-lpm" class="nav-link" data-scroll-target="#summary-logit-vs.-probit-vs.-lpm"><span class="header-section-number">4</span> Summary: Logit vs.&nbsp;Probit vs.&nbsp;LPM</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_introduction.html">Basics</a></li><li class="breadcrumb-item"><a href="./09_Logistic_Regression.html">Regression with a Binary Dependent Variable</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Regression with a Binary Dependent Variable</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>🎯 <strong>Study Objectives</strong></p>
<ul>
<li>Understand why linear regression is inappropriate for binary dependent variables.</li>
<li>Learn the logit and probit models for analyzing binary outcomes.</li>
<li>Interpret coefficients in logistic regressions.</li>
<li>Apply logit/probit models using real-world data (HMDA mortgage application dataset).</li>
<li>Understand the concept of predicted probabilities.</li>
<li>Compare linear probability model (LPM), logit, and probit approaches.</li>
</ul>
</div>
</div>
</div>
<section id="why-binary-dependent-variables-require-special-treatment" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="why-binary-dependent-variables-require-special-treatment"><span class="header-section-number">1</span> Why Binary Dependent Variables Require Special Treatment</h2>
<p>In many economic and financial applications, the dependent variable is <strong>binary</strong> (takes only two values: 0 or 1). Examples include:</p>
<ul>
<li><strong>Mortgage approval</strong>: Did the bank approve the mortgage application? (Yes = 1, No = 0)</li>
<li><strong>Labor force participation</strong>: Is the individual employed? (Yes = 1, No = 0)</li>
<li><strong>Default risk</strong>: Did the borrower default on the loan? (Yes = 1, No = 0)</li>
<li><strong>Market entry</strong>: Does the firm enter the market? (Yes = 1, No = 0)</li>
<li><strong>Product choice</strong>: Does the consumer purchase the product? (Yes = 1, No = 0)</li>
</ul>
<section id="why-linear-regression-fails" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="why-linear-regression-fails"><span class="header-section-number">1.1</span> Why Linear Regression Fails</h3>
<p>If we try to use ordinary linear regression (OLS) with a binary dependent variable <span class="math inline">\(Y_i \in \{0,1\}\)</span>:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \cdots + \beta_k X_{ki} + u_i
\]</span></p>
<p>This approach is called the <strong>Linear Probability Model (LPM)</strong> because it estimates the probability that <span class="math inline">\(Y_i = 1\)</span> as a linear function of the predictors.</p>
<p><strong>Problems with LPM:</strong></p>
<ol type="1">
<li><p><strong>Predicted probabilities outside [0,1]</strong>: OLS can produce fitted values <span class="math inline">\(\hat{Y}_i &lt; 0\)</span> or <span class="math inline">\(\hat{Y}_i &gt; 1\)</span>, which makes no sense for probabilities.</p></li>
<li><p><strong>Heteroskedasticity</strong>: The error term variance depends on <span class="math inline">\(X\)</span>, violating the homoskedasticity assumption. This means standard errors are incorrect.</p></li>
<li><p><strong>Nonlinear relationship</strong>: The effect of <span class="math inline">\(X\)</span> on the probability of <span class="math inline">\(Y=1\)</span> is unlikely to be constant across all values of <span class="math inline">\(X\)</span>. For example, increasing income from \$20,000 to \$30,000 likely has a different effect on mortgage approval than increasing from \$200,000 to \$210,000.</p></li>
</ol>
</section>
<section id="the-solution-logit-and-probit-models" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="the-solution-logit-and-probit-models"><span class="header-section-number">1.2</span> The Solution: Logit and Probit Models</h3>
<p>To address these problems, we use <strong>nonlinear models</strong> that ensure predicted probabilities stay within [0,1]:</p>
<ul>
<li><strong>Logit model</strong>: Uses the logistic cumulative distribution function (CDF)</li>
<li><strong>Probit model</strong>: Uses the standard normal cumulative distribution function (CDF)</li>
</ul>
</section>
</section>
<section id="the-hmda-dataset-mortgage-lending-discrimination" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-hmda-dataset-mortgage-lending-discrimination"><span class="header-section-number">2</span> The HMDA Dataset: Mortgage Lending Discrimination</h2>
<p>We will use data from the <strong>Federal Reserve Bank of Boston</strong> collected under the <strong>Home Mortgage Disclosure Act (HMDA)</strong>. The dataset contains information on mortgage applications in the Boston area in 1990. The dataset contains 2380 observations with 14 variables.</p>
<p><strong>Research Question:</strong> Do banks discriminate against minority applicants when making mortgage lending decisions, after controlling for economic factors?</p>
<section id="load-the-data" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="load-the-data"><span class="header-section-number">2.1</span> Load the Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"AER"</span>, <span class="st">"tidyverse"</span>, <span class="st">"stargazer"</span>, <span class="st">"margins"</span>, <span class="st">"data.table"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(pkgs, <span class="fu">rownames</span>(<span class="fu">installed.packages</span>()))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">install.packages</span>(missing)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">lapply</span>(pkgs, <span class="cf">function</span>(pkg) <span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(pkg, <span class="at">character.only =</span> <span class="cn">TRUE</span>))))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load HMDA data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HMDA"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the data</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">data.table</span>(HMDA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        deny pirat hirat     lvrat  chist  mhist  phist unemp selfemp insurance
      &lt;fctr&gt; &lt;num&gt; &lt;num&gt;     &lt;num&gt; &lt;fctr&gt; &lt;fctr&gt; &lt;fctr&gt; &lt;num&gt;  &lt;fctr&gt;    &lt;fctr&gt;
   1:     no 0.221 0.221 0.8000000      5      2     no   3.9      no        no
   2:     no 0.265 0.265 0.9218750      2      2     no   3.2      no        no
   3:     no 0.372 0.248 0.9203980      1      2     no   3.2      no        no
   4:     no 0.320 0.250 0.8604651      1      2     no   4.3      no        no
   5:     no 0.360 0.350 0.6000000      1      1     no   3.2      no        no
  ---                                                                          
2376:     no 0.310 0.250 0.8000000      1      1     no   3.2     yes        no
2377:     no 0.300 0.300 0.7770492      1      2     no   3.2      no        no
2378:     no 0.260 0.200 0.5267606      2      1     no   3.1      no        no
2379:    yes 0.320 0.260 0.7538462      6      1    yes   3.1      no        no
2380:    yes 0.350 0.260 0.8135593      2      2     no   4.3      no        no
      condomin   afam single hschool
        &lt;fctr&gt; &lt;fctr&gt; &lt;fctr&gt;  &lt;fctr&gt;
   1:       no     no     no     yes
   2:       no     no    yes     yes
   3:       no     no     no     yes
   4:       no     no     no     yes
   5:       no     no     no     yes
  ---                               
2376:       no     no     no     yes
2377:      yes     no    yes     yes
2378:       no     no     no     yes
2379:      yes    yes    yes     yes
2380:      yes     no    yes     yes</code></pre>
</div>
</div>
</section>
<section id="variable-definitions" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="variable-definitions"><span class="header-section-number">2.2</span> Variable Definitions</h3>
<p>The key variables in the HMDA dataset are:</p>
<ul>
<li>We will mainly use <code>deny</code>, <code>pirat</code>, and <code>afam</code> in our analysis.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="env-green"><code>deny</code></span></td>
<td>Was the mortgage application denied? (yes/no) — <strong>dependent variable</strong></td>
</tr>
<tr class="even">
<td><span class="env-green"><code>pirat</code></span></td>
<td>Payments-to-income ratio (monthly loan payments / monthly income)</td>
</tr>
<tr class="odd">
<td><span class="env-green"><code>afam</code></span></td>
<td>Is the applicant African American? (yes/no)</td>
</tr>
<tr class="even">
<td><code>hirat</code></td>
<td>Housing expense-to-income ratio (monthly housing expenses / monthly income)</td>
</tr>
<tr class="odd">
<td><code>lvrat</code></td>
<td>Loan-to-value ratio (loan amount / assessed property value)</td>
</tr>
<tr class="even">
<td><code>chist</code></td>
<td>Credit history: consumer credit score</td>
</tr>
<tr class="odd">
<td><code>mhist</code></td>
<td>Mortgage history: mortgage credit score</td>
</tr>
<tr class="even">
<td><code>phist</code></td>
<td>Public record history: coded as “no” or “yes” (any bankruptcies, tax liens, etc.)</td>
</tr>
<tr class="odd">
<td><code>insurance</code></td>
<td>Was mortgage insurance denied? (yes/no)</td>
</tr>
<tr class="even">
<td><code>selfemp</code></td>
<td>Is the applicant self-employed? (yes/no)</td>
</tr>
<tr class="odd">
<td><code>single</code></td>
<td>Is the applicant single? (yes/no)</td>
</tr>
<tr class="even">
<td><code>hschool</code></td>
<td>Does the applicant have high school education? (yes/no)</td>
</tr>
<tr class="odd">
<td><code>unemp</code></td>
<td>1989 Massachusetts unemployment rate in applicant’s industry (%).</td>
</tr>
<tr class="even">
<td><code>condominium</code></td>
<td>Is the property a condominium? (yes/no)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-exploration" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="data-exploration"><span class="header-section-number">2.3</span> Data Exploration</h3>
<section id="frequency-tables-and-contingency-tables" class="level4">
<h4 class="anchored" data-anchor-id="frequency-tables-and-contingency-tables">Frequency Tables and Contingency Tables</h4>
<p><strong>Let’s examine the denial rates overall and by race.</strong></p>
<p>We first look at the overall denial counts and rates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall denial counts</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Overall Denial Counts:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(HMDA, <span class="fu">table</span>(deny))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall denial rate</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===========================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Overall Denial Rate:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(HMDA, <span class="fu">prop.table</span>(<span class="fu">table</span>(deny))) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Denial Counts:
deny
  no  yes 
2095  285 
===========================
Overall Denial Rate:
deny
  no  yes 
0.88 0.12 </code></pre>
</div>
</div>
<p>The table shows that about 12% of mortgage applications were denied overall. The majority of applications (88%) were approved.</p>
<p>Next, we examine denial counts and rates by race.</p>
<p>A <span class="env-green"><strong>contingency table</strong></span> is an effective method to see the association between two categorical variables. It counts the number of observations in each of the four possible scenarios. When dealing with just one categorical variable, this is referred to as a <strong>frequency table</strong>, which count the number of observations for each category.</p>
<p>The following gives a 2x2 contingency table for mortgage denial by African-American or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Denial rate by race</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Denail counts by race:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(HMDA, <span class="fu">table</span>(deny, afam))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===========================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Denial rate by race:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(HMDA, <span class="fu">prop.table</span>(<span class="fu">table</span>(deny, afam), <span class="at">margin =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Denail counts by race:
     afam
deny    no  yes
  no  1852  243
  yes  189   96
===========================
Denial rate by race:
     afam
deny     no   yes
  no  0.907 0.717
  yes 0.093 0.283</code></pre>
</div>
</div>
<p>Some observations from the table:</p>
<ul>
<li>The majority of applicants are non-African American.</li>
<li>African American applicants have a higher denial rate (about 28%) compared to non-African American applicants (about 9%).</li>
</ul>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>This descriptive evidence suggests that <em>the likelihood of denial may be systematically higher for African American applicants</em>. However, these simple proportions do not control for other relevant factors such as income, credit history, or loan-to-value ratio. Logistic regression will allow us to model this relationship more rigorously while accounting for these additional variables.</p>
</div>
</div>
</div>
</section>
<section id="summary-statistics" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HMDA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  deny          pirat            hirat            lvrat        chist   
 no :2095   Min.   :0.0000   Min.   :0.0000   Min.   :0.0200   1:1353  
 yes: 285   1st Qu.:0.2800   1st Qu.:0.2140   1st Qu.:0.6527   2: 441  
            Median :0.3300   Median :0.2600   Median :0.7795   3: 126  
            Mean   :0.3308   Mean   :0.2553   Mean   :0.7378   4:  77  
            3rd Qu.:0.3700   3rd Qu.:0.2988   3rd Qu.:0.8685   5: 182  
            Max.   :3.0000   Max.   :3.0000   Max.   :1.9500   6: 201  
 mhist    phist          unemp        selfemp    insurance  condomin  
 1: 747   no :2205   Min.   : 1.800   no :2103   no :2332   no :1694  
 2:1571   yes: 175   1st Qu.: 3.100   yes: 277   yes:  48   yes: 686  
 3:  41              Median : 3.200                                   
 4:  21              Mean   : 3.774                                   
                     3rd Qu.: 3.900                                   
                     Max.   :10.600                                   
  afam      single     hschool   
 no :2041   no :1444   no :  39  
 yes: 339   yes: 936   yes:2341  
                                 
                                 
                                 
                                 </code></pre>
</div>
</div>
<p>Summary statistics by race.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics by race</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>HMDA <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(afam) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">denial_rate =</span> <span class="fu">mean</span>(deny <span class="sc">==</span> <span class="st">"yes"</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">mean_pirat =</span> <span class="fu">mean</span>(pirat),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">mean_lvrat =</span> <span class="fu">mean</span>(lvrat)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  afam      n denial_rate mean_pirat mean_lvrat
  &lt;fct&gt; &lt;int&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1 no     2041  0.09260167  0.3274625  0.7259712
2 yes     339  0.2831858   0.3509891  0.8088478</code></pre>
</div>
</div>
</section>
</section>
<section id="visualizing-the-contingency-table" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="visualizing-the-contingency-table"><span class="header-section-number">2.4</span> Visualizing the Contingency Table</h3>
<p>We can visualize the contingency table using a <strong>Stacked Bar Plot</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09_Logistic_Regression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The stacked bar graph shows:</p>
<ul>
<li>The sample sizes of African American and non-African American applicants</li>
<li>The distribution of approved vs.&nbsp;denied applications within each racial group</li>
<li>African American applicants appear to have a higher proportion of denials</li>
</ul>
<p>Issue: When the groups have very different sizes, it can be hard to compare proportions using absolute frequencies.</p>
<p>Remedy: Use a <strong>mosaic plot</strong> to visualize <strong>relative frequencies</strong>.</p>
<section id="mosaic-plot" class="level4">
<h4 class="anchored" data-anchor-id="mosaic-plot">Mosaic Plot</h4>
<p>A mosaic plot replaces absolute frequencies with relative frequencies, making it easier to compare proportions across groups.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09_Logistic_Regression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>The widths of the boxes are proportional to the percentage of each racial group in the sample.</li>
<li>The heights represent the denial rates within each group.</li>
<li>We can see that the “Denied” box for African American applicants is taller than for non-African American applicants, indicating a higher denial rate.</li>
</ul>
</section>
</section>
<section id="measures-of-risk-and-association-for-binary-outcomes" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="measures-of-risk-and-association-for-binary-outcomes"><span class="header-section-number">2.5</span> Measures of Risk and Association for Binary Outcomes</h3>
<p>To quantify the difference in mortgage denial rates between racial groups, we can calculate several measures of risk and association.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate risk (denial rate) for each group</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>risk_table <span class="ot">&lt;-</span> contingency_table <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(<span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.data.frame.matrix</span>()</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>risk_table <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">3</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract probabilities</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>p_non_afam <span class="ot">&lt;-</span> risk_table[<span class="st">"Denied"</span>, <span class="st">"Non-African American"</span>] <span class="co"># P(deny=1 | afam=0)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>p_afam <span class="ot">&lt;-</span> risk_table[<span class="st">"Denied"</span>, <span class="st">"African American"</span>] <span class="co"># P(deny=1 | afam=1)</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Risk (Denial Rate) by Race:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===========================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Non-African American: %.4f (%.2f%%)</span><span class="sc">\n</span><span class="st">"</span>, p_non_afam, p_non_afam <span class="sc">*</span> <span class="dv">100</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"African American:     %.4f (%.2f%%)</span><span class="sc">\n</span><span class="st">"</span>, p_afam, p_afam <span class="sc">*</span> <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Non-African American African American
Approved                0.907            0.717
Denied                  0.093            0.283

Risk (Denial Rate) by Race:
===========================
Non-African American: 0.0926 (9.26%)
African American:     0.2832 (28.32%)</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>Risk Difference (Excess Risk)</strong></p>
<p>The <strong>risk difference</strong> or <strong>excess risk</strong> (ER) is the difference in denial rates between the two groups:</p>
<p><span class="math display">\[
ER = P(\text{deny}=1|\text{afam}=1) - P(\text{deny}=1|\text{afam}=0)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>ER <span class="ot">&lt;-</span> p_afam <span class="sc">-</span> p_non_afam</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Risk Difference (Excess Risk):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"==============================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"ER = %.4f - %.4f = %.4f (%.2f percentage points)</span><span class="sc">\n</span><span class="st">"</span>, p_afam, p_non_afam, ER, ER <span class="sc">*</span> <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Risk Difference (Excess Risk):
==============================
ER = 0.2832 - 0.0926 = 0.1906 (19.06 percentage points)</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> African American applicants have a denial rate that is 19.06 percentage points higher than non-African American applicants.</p>
<ul>
<li><p>If <span class="math inline">\(ER = 0\)</span>: no difference in risk between groups</p></li>
<li><p>If <span class="math inline">\(ER &gt; 0\)</span>: higher risk for the <span class="env-green">treatment group</span> (African Americans, <code>afam=1</code>)</p>
<p>By contrast, the <span class="env-green">control group</span> is non-African Americans (<code>afam=0</code>).</p></li>
<li><p>If <span class="math inline">\(ER &lt; 0\)</span>: lower risk for the treatment group</p></li>
</ul></li>
<li><p><strong>Risk Ratio (Relative Risk)</strong></p>
<p>The <strong>risk ratio</strong> or <strong>relative risk</strong> (RR) is the ratio of denial rates:</p>
<p><span class="math display">\[
RR = \frac{P(\text{deny}=1|\text{afam}=1)}{P(\text{deny}=1|\text{afam}=0)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>RR <span class="ot">&lt;-</span> p_afam <span class="sc">/</span> p_non_afam</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Risk Ratio (Relative Risk):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===========================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"RR = %.4f / %.4f = %.4f</span><span class="sc">\n</span><span class="st">"</span>, p_afam, p_non_afam, RR))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Risk Ratio (Relative Risk):
===========================
RR = 0.2832 / 0.0926 = 3.0581</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> African American applicants have a denial rate that is 3.06 times higher than non-African American applicants.</p>
<ul>
<li>If <span class="math inline">\(RR = 1\)</span>: no difference in risk</li>
<li>If <span class="math inline">\(RR &gt; 1\)</span>: higher risk for the treatment group (African Americans, <code>afam=1</code>)</li>
<li>If <span class="math inline">\(RR &lt; 1\)</span>: lower risk for the treatment group</li>
</ul></li>
<li><p><strong>Odds Ratio</strong></p>
<p>The <strong>odds ratio</strong> (OR) compares the odds of denial between the two groups.</p>
<p>First, calculate the odds for each group:</p>
<p><span class="math display">\[
\text{odds} = \frac{P(\text{deny}=1)}{P(\text{deny}=0)} = \frac{P(\text{deny}=1)}{1 - P(\text{deny}=1)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate odds for each group</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>odds_non_afam <span class="ot">&lt;-</span> p_non_afam <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p_non_afam)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>odds_afam <span class="ot">&lt;-</span> p_afam <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p_afam)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Odds by Race:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"=============</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Non-African American: %.4f</span><span class="sc">\n</span><span class="st">"</span>, odds_non_afam))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"African American:     %.4f</span><span class="sc">\n</span><span class="st">"</span>, odds_afam))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Odds by Race:
=============
Non-African American: 0.1021
African American:     0.3951</code></pre>
</div>
</div>
<p>This means that the odds of being denied a mortgage are approximately <strong>0.10 for non–African American applicants</strong> and <strong>0.40 for African American applicants</strong>.</p>
<p>The odds ratio is:</p>
<p><span class="math display">\[
OR = \frac{\text{odds}(\text{afam}=1)}{\text{odds}(\text{afam}=0)} = \frac{P(\text{deny}=1|\text{afam}=1)/[1-P(\text{deny}=1|\text{afam}=1)]}{P(\text{deny}=1|\text{afam}=0)/[1-P(\text{deny}=1|\text{afam}=0)]}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> odds_afam <span class="sc">/</span> odds_non_afam</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Odds Ratio:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===========</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"OR = %.4f/%.4f = %.4f</span><span class="sc">\n</span><span class="st">"</span>, odds_afam, odds_non_afam, OR))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Odds Ratio:
===========
OR = 0.3951/0.1021 = 3.8712</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> The odds of mortgage denial for African American applicants are 3.87 times higher than the odds for non-African American applicants.</p>
<ul>
<li>If <span class="math inline">\(OR = 1\)</span>: no difference in odds</li>
<li>If <span class="math inline">\(OR &gt; 1\)</span>: higher odds for the treatment group (African Americans, <code>afam=1</code>)</li>
<li>If <span class="math inline">\(OR &lt; 1\)</span>: lower odds for the treatment group</li>
</ul></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important Distinction
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Risk difference</strong> measures the absolute difference in probabilities (additive scale)</p></li>
<li><p><strong>Risk ratio</strong> and <strong>odds ratio</strong> measure relative differences (multiplicative scale)</p></li>
<li><p>The odds ratio is particularly useful because <span class="env-green">it directly relates to the coefficient in logistic regression</span>:</p>
<p>When we estimate a logistic model with <code>afam</code> as the predictor, <span class="math inline">\(e^{\beta_{\text{afam}}}\)</span> will equal the odds ratio we calculated here.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="model-specification-the-boston-mortgage-example" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="model-specification-the-boston-mortgage-example"><span class="header-section-number">3</span> Model Specification: The Boston Mortgage Example</h2>
<p>We want to model the probability that a mortgage application is denied as a function of applicant characteristics.</p>
<section id="preparing-the-data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="preparing-the-data"><span class="header-section-number">3.1</span> Preparing the Data</h3>
<p>First, we create a binary numeric variable for denial (1 = denied, 0 = approved) and recode some factors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create binary dependent variable</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>HMDA<span class="sc">$</span>deny_binary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(HMDA<span class="sc">$</span>deny <span class="sc">==</span> <span class="st">"yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create binary variable for African American</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>HMDA<span class="sc">$</span>afam_binary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(HMDA<span class="sc">$</span>afam <span class="sc">==</span> <span class="st">"yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the variables</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(HMDA[, <span class="fu">c</span>(<span class="st">"deny"</span>, <span class="st">"deny_binary"</span>, <span class="st">"pirat"</span>, <span class="st">"afam"</span>, <span class="st">"afam_binary"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  deny deny_binary pirat afam afam_binary
1   no           0 0.221   no           0
2   no           0 0.265   no           0
3   no           0 0.372   no           0
4   no           0 0.320   no           0
5   no           0 0.360   no           0
6   no           0 0.240   no           0</code></pre>
</div>
</div>
</section>
<section id="model-1-linear-probability-model" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="model-1-linear-probability-model"><span class="header-section-number">3.2</span> Model 1: Linear Probability Model</h3>
<p>Let’s start with a simple linear regression to see its limitations.</p>
<p>The OLS regression of the binary dependent variable, <span class="math inline">\(deny\)</span> against the payment-to-income ratio (<code>pirat</code>), is estimated as:</p>
<p><span class="math display">\[
deny = \beta_0 + \beta_1 \cdot pirat + \varepsilon
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lpm_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(deny_binary <span class="sc">~</span> pirat, <span class="at">data =</span> HMDA)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(lpm_simple, <span class="at">vcov. =</span> vcovHC, <span class="at">type =</span> <span class="st">"HC1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) -0.079910   0.031967 -2.4998   0.01249 *  
pirat        0.603535   0.098483  6.1283 1.036e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><span class="math display">\[
\widehat{deny} = -0.080 + 0.604 \cdot pirat
\]</span></p>
<p>The estimated coefficient on P/I ratio is positive, and the population coefficient is statistically significantly different from 0 at the 1% level (the t-statistic is 6.12). If P/I ratio increases by 0.1, the probability of denial increases by approximately <span class="math inline">\(0.604\times 0.1 \approx 0.060,\)</span> that is, by 6 percentage points. Thus applicants with higher debt payments as a fraction of income are more likely to have their application denied.</p>
<p>Now we plot the data and the regression line to visualize the model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-linear" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09_Logistic_Regression_files/figure-html/fig-linear-1.png" id="fig-linear" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled" title="Shortcomings with the linear probability model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Shortcomings with the linear probability model
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The linear probability model can predict probabilities outside the <span class="math inline">\([0,1]\)</span> range. For example, for high values of P/I ratio (<code>pirat</code>), the predicted probability exceeds 1. However, probabilities must lie between 0 and 1.</p></li>
<li><p>The relationship between P/I ratio and the probability of denial may NOT be linear in reality.</p>
<p>It is reasonable to expect the marginal effects of P/I ratio on denial probability to diminish as P/I ratio increases.</p>
<p>Although a change in P/I ratio from 0.3 to 0.4 might have a large effect on the probability of denial, once the P/I ratio is already very high (e.g., 0.9 to 1.0), increasing P/I ratio further will have litte effect.</p></li>
<li><p>The error term in the linear probability model is <em>heteroskedastic</em>, violating OLS assumptions.</p>
<p>This means that standard errors and hypothesis tests based on OLS are invalid. → This issue can be addressed using heteroskedasticity robust standard errors.</p></li>
</ol>
</div>
</div>
</section>
<section id="model-2-logit-regression-with-a-single-predictor" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="model-2-logit-regression-with-a-single-predictor"><span class="header-section-number">3.3</span> Model 2: Logit Regression with a single predictor</h3>
<p>The estimated model is <span class="math display">\[
\mathrm P(deny_i = 1 | pirat_i) = F(\beta_0 + \beta_1 \cdot pirat_i) = \frac{1}{1 + e^{-(\beta_0 + \beta_1 \cdot pirat_i)}} ,
\]</span></p>
<p>where <span class="math inline">\(F\)</span> is the logistic distribution function.</p>
<p>Note that the left-hand side is the probability that the <span class="math inline">\(i\)</span>-th mortgage application is denied (<span class="math inline">\(deny_i = 1\)</span>), given the payment-to-income ratio (<span class="math inline">\(pirat_i\)</span>).</p>
<p>The strength of the logit model is that <span class="env-green">it ensures predicted probabilities are always between 0 and 1</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate logit model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>logit_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(deny_binary <span class="sc">~</span> pirat,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> HMDA</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(logit_simple, <span class="at">vcov. =</span> vcovHC, <span class="at">type =</span> <span class="st">"HC1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
z test of coefficients:

            Estimate Std. Error  z value  Pr(&gt;|z|)    
(Intercept) -4.02843    0.35898 -11.2218 &lt; 2.2e-16 ***
pirat        5.88450    1.00015   5.8836 4.014e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><span class="math display">\[
\widehat{\mathrm P}(deny_i = 1 | pirat_i) = F(-4.02 + 5.88 \cdot pirat_i)= \frac{1}{1 + e^{-(-4.02 + 5.88 \cdot pirat_i)}}
\]</span></p>
<p>Visualizing the logit model:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-logit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09_Logistic_Regression_files/figure-html/fig-logit-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The logit model uses the logistic distribution function to model the probability of denial as a function of the payment-to-income ratio. Unlike the linear probability model, the logit model ensures predicted probabilities remain within the [0,1] range.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The estimated logit regression function has a stretched “S” shape: It is nearly 0 and flat for small values of P/I ratio, it turns and increases for intermediate values, and it flattens out again and is nearly 1 for large values.</p>
<div id="exm-1" class="example theorem">
<p><span class="theorem-title"><strong>Example 1</strong></span> <strong>Predicted probability.</strong></p>
<p>What is the probability of denial given a P/I ratio of 0.3? What about for P/I ratio being 0.4 and 0.5?</p>
</div>
<button class="solution-btn" onclick="myFunction('sol-1')">
Solution
</button>
<div id="sol-1" class="solution-answer env-green proof solution">
<p><span class="proof-title"><em>Solution 1</em>. </span>For P/I ratio of 0.3, the estimated probability of denial based on the estimated logit model is: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.3) = \frac{1}{1 + e^{-(-4.02 + 5.88 \cdot 0.3)}} \approx 9.4\%
\]</span> That is, the probability of denial is approximately 9.4%.</p>
<p>For P/I ratio of 0.4: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.4) = \frac{1}{1 + e^{-(-4.02 + 5.88 \cdot 0.4)}} \approx 15.7\%
\]</span> That is, the probability of denial is approximately 15.7%.</p>
<p>For P/I ratio of 0.5: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.5) = \frac{1}{1 + e^{-(-4.02 + 5.88 \cdot 0.5)}} \approx 25.2\%
\]</span></p>
<p><strong>Main takeaway:</strong> As P/I ratio increases, the probability of denial increases, but not linearly.</p>
</div>
<p><span class="env-green"><strong>Interpretation on the logit coefficients:</strong></span></p>
<p>The estimated model is</p>
<p><span class="math display">\[
\widehat{P}(deny_i = 1 \mid pirat_i) = \frac{1}{1 + e^{-(-4.02 + 5.88 \cdot pirat_i)}}
\]</span></p>
<p>which can be written in <strong>log-odds form</strong> as</p>
<p><span class="math display">\[
\log\left(\frac{P(deny_i = 1)}{1 - P(deny_i = 1)}\right) = -4.02 + 5.88 \cdot pirat_i
\]</span></p>
<ol type="1">
<li><p><strong>Interpreting coefficients (log-odds scale):</strong></p>
<p>The slope coefficient, <span class="math inline">\(\hat{\beta}_1 = 5.88\)</span>, means that a <strong>one-unit increase</strong> in <code>pirat</code> increases the <strong>log-odds</strong> of mortgage denial by <strong>5.88</strong>, holding all else constant.</p></li>
<li><p><strong>Interpreting odds ratios (exponentiating coefficients):</strong></p>
<p>To obtain a more intuitive interpretation, we exponentiate the coefficient: <span class="math display">\[
e^{\hat{\beta}_1} = e^{5.88} \approx 357.7
\]</span> This means that for a <strong>one-unit increase</strong> in the payment-to-income ratio, the <strong>odds</strong> of mortgage denial are about <strong>357.7 times larger</strong>.</p>
<ul>
<li>Because a one-unit increase in <code>pirat</code> is very large in practice, it is often more meaningful to interpret smaller changes.</li>
</ul>
<p>For example, for a <strong>0.1 increase</strong> in <code>pirat</code>: <span class="math display">\[
e^{5.88 \times 0.1} \approx 1.80
\]</span> This means that a 0.1 increase in the payment-to-income ratio increases the <strong>odds of denial by about 80%</strong>.</p></li>
</ol>
<p><strong>Hypothesis Testing:</strong></p>
<p>Using the normal distribution of parameter estimates, we can use the standard normal table rather than the <span class="math inline">\(t\)</span> table for critical points to test hypotheses about the coefficients.</p>
<p>The <span class="math inline">\(z\)</span>-statistic for testing <span class="math inline">\(H_0: \beta_1 = 0\)</span> is:</p>
<p><span class="math display">\[
z = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)} = \frac{5.88 - 0}{1} \approx 5.88
\]</span></p>
<p>Since <span class="math inline">\(z &gt; 1.96\)</span>, we reject the null hypothesis at the 5% significance level and conclude that there is a statistically significant positive relationship between payment-to-income ratio and the probability of mortgage denial.</p>
</section>
<section id="model-3-linear-probability-model-with-multiple-predictors" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="model-3-linear-probability-model-with-multiple-predictors"><span class="header-section-number">3.4</span> Model 3: Linear Probability Model with Multiple Predictors</h3>
<p><span class="math display">\[
deny_i = \beta_0 + \beta_1 \cdot pirat_i + \beta_2 \cdot afam_i
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate LPM</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>lpm_multi <span class="ot">&lt;-</span> <span class="fu">lm</span>(deny_binary <span class="sc">~</span> pirat <span class="sc">+</span> afam_binary, <span class="at">data =</span> HMDA)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lpm_multi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = deny_binary ~ pirat + afam_binary, data = HMDA)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.62526 -0.11772 -0.09293 -0.05488  1.06815 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.09051    0.02079  -4.354 1.39e-05 ***
pirat        0.55919    0.05987   9.340  &lt; 2e-16 ***
afam_binary  0.17743    0.01837   9.659  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3123 on 2377 degrees of freedom
Multiple R-squared:  0.076, Adjusted R-squared:  0.07523 
F-statistic: 97.76 on 2 and 2377 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><span class="math inline">\(\hat{\beta}_1\)</span>: A one-unit increase in the payment-to-income ratio increases the probability of denial by approximately <span class="math inline">\(\hat{\beta}_1\)</span>.</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span>: African American applicants have a probability of denial that is <span class="math inline">\(\hat{\beta}_2\)</span> percentage points higher than non-African American applicants, holding <code>pirat</code> constant.</li>
</ul>
</section>
<section id="model-4-logit-model-with-multiple-predictors" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="model-4-logit-model-with-multiple-predictors"><span class="header-section-number">3.5</span> Model 4: Logit Model with Multiple Predictors</h3>
<p>Now we estimate a logit model including both P/I ratio (<code>pirat</code>) and African-American binary (<code>afam_binary</code>) as predictors:</p>
<p><span class="math display">\[
P(deny_i = 1 | pirat_i, afam_i) = F(\beta_0 + \beta_1 \cdot pirat_i + \beta_2 \cdot afam_i) = \frac{1}{1 + e^{-(\beta_0 + \beta_1 \cdot pirat_i + \beta_2 \cdot afam_i)}} .
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate logit model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>logit_multi <span class="ot">&lt;-</span> <span class="fu">glm</span>(deny_binary <span class="sc">~</span> pirat <span class="sc">+</span> afam_binary,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> HMDA</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(logit_multi, <span class="at">vcov. =</span> vcovHC, <span class="at">type =</span> <span class="st">"HC1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
z test of coefficients:

            Estimate Std. Error  z value  Pr(&gt;|z|)    
(Intercept) -4.12556    0.34597 -11.9245 &lt; 2.2e-16 ***
pirat        5.37036    0.96376   5.5723 2.514e-08 ***
afam_binary  1.27278    0.14616   8.7081 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The estimated logit model is: <span class="math display">\[
\begin{split}
\widehat{P}(deny_i = 1 | pirat_i, afam_i) &amp;= F(-4.13 + 5.37 \cdot pirat_i + 1.27 \cdot afam_i) \\
&amp;= \frac{1}{1 + e^{-(-4.13 + 5.37 \cdot pirat_i + 1.27 \cdot afam_i)}}
\end{split}
\]</span></p>
<p><span class="env-green"><strong>Interpretation of Logit Coefficients</strong></span></p>
<p>The coefficients in a logit model represent the change in the <strong>log-odds</strong> of denial:</p>
<p><span class="math display">\[
\log\left(\frac{P(deny = 1)}{1 - P(deny = 1)}\right) = -4.13 + 5.37 \cdot pirat_i + 1.27 \cdot afam_i
\]</span></p>
<p><strong>1. Interpreting coefficients (log-odds scale):</strong></p>
<ul>
<li><span class="math inline">\(\hat{\beta}_1 &gt; 0\)</span>: A one-unit increase in <code>pirat</code> increases the log-odds of denial by <span class="math inline">\(\hat{\beta}_1\)</span>, holding other variables constant.</li>
<li><span class="math inline">\(\hat{\beta}_2 &gt; 0\)</span>: Being African American increases the log-odds of denial by <span class="math inline">\(\hat{\beta}_2\)</span> compared to non-African Americans, holding other variables constant.</li>
</ul>
<p><strong>2. Interpreting odds ratios (exponentiating coefficients):</strong></p>
<p>Alternatively, we can interpret the <strong>odds ratio</strong> by taking the exponential of the coefficients:</p>
<ul>
<li><p><strong>For <code>pirat</code></strong>: <span class="math inline">\(e^{\hat{\beta}_1}\)</span> represents the <strong>multiplicative change in odds</strong> for a one-unit increase in the payment-to-income ratio.</p>
<p>For example, if the P/I ratio increases by 0.2, then <span class="math inline">\(e^{5.37\times 0.2} = 2.93\)</span>, that is, the odds of mortgage denial are approximately 2.94 times higher, holding <code>afam</code> constant.</p></li>
<li><p><strong>For <code>afam</code></strong>: <span class="math inline">\(e^{\hat{\beta}_2}\)</span> is the <strong>odds ratio comparing African American applicants to non-African American applicants</strong>.</p>
<p>Based on the estimates, <span class="math inline">\(e^{1.2} = 3.56\)</span>, that is, African American applicants have odds of denial that are 3.56 times higher than non-African American applicants, holding <code>pirat</code> constant.</p></li>
</ul>
<div id="exm-2" class="example theorem">
<p><span class="theorem-title"><strong>Example 2</strong></span> Suppose we have:</p>
<ul>
<li>Odds of denial for a non-African American applicant with <code>pirat = 0.3</code> is 0.15</li>
<li>The odds ratio for African Americans compared to non-African American is <span class="math inline">\(e^{\hat{\beta}_2} = 3.56\)</span></li>
</ul>
<p>Calculate the expected odds for an African American applicant with the same <code>pirat = 0.3</code>.</p>
</div>
<button class="solution-btn" onclick="myFunction('sol-2')">
Solution
</button>
<div id="sol-2" class="solution-answer env-green proof solution">
<p><span class="proof-title"><em>Solution 2</em>. </span><span class="math display">\[
\text{odds}(\text{afam}=1) = \text{odds}(\text{afam}=0) \times e^{\hat{\beta}_2} = 0.15 \times 3.56 = 0.534
\]</span> The expected odds of denial for an African American applicant with <code>pirat = 0.3</code> is 0.534.</p>
</div>
</section>
<section id="model-5-probit-model" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="model-5-probit-model"><span class="header-section-number">3.6</span> Model 5: Probit Model</h3>
<p>In contrast to the logit model, which uses the logistic CDF, the probit model uses the <span class="env-green">standard normal</span> distribution function to model the probability of denial. <span class="math display">\[
P(deny_i = 1 | X_i) = \Phi(\beta_0 + \beta_1 \cdot pirat_i + \beta_2 \cdot afam_i)
\]</span></p>
<p>where <span class="math inline">\(\Phi(\cdot)\)</span> is the standard normal CDF.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate probit model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>probit_multi <span class="ot">&lt;-</span> <span class="fu">glm</span>(deny_binary <span class="sc">~</span> pirat <span class="sc">+</span> afam_binary,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> HMDA</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(probit_multi, <span class="at">vcov. =</span> vcovHC, <span class="at">type =</span> <span class="st">"HC1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
z test of coefficients:

             Estimate Std. Error  z value  Pr(&gt;|z|)    
(Intercept) -2.258787   0.176608 -12.7898 &lt; 2.2e-16 ***
pirat        2.741779   0.497673   5.5092 3.605e-08 ***
afam_binary  0.708155   0.083091   8.5227 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="comparison-logit-and-probit" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="comparison-logit-and-probit"><span class="header-section-number">3.7</span> Comparison: Logit, and Probit</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09_Logistic_Regression_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Practical Recommendation:</strong></p>
<ul>
<li>Logit and probit typically give very similar results.</li>
<li>Logit is more common in economics and finance due to the convenient odds ratio interpretation.</li>
</ul>
</section>
<section id="predicted-probabilities" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="predicted-probabilities"><span class="header-section-number">3.8</span> Predicted Probabilities</h3>
<p>To compare effects across models, we calculate <strong>predicted probabilities</strong> at specific values of the predictors.</p>
<div id="exm-3" class="example theorem">
<p><span class="theorem-title"><strong>Example 3</strong></span> For the three multivariate models (models 3–5), what is the predicted probability of denial for:</p>
<ul>
<li>An African American applicant with <code>pirat = 0.3</code>?</li>
<li>A non-African American applicant with <code>pirat = 0.3</code>?</li>
</ul>
</div>
<button class="solution-btn" onclick="myFunction('sol-3')">
Solution
</button>
<div id="sol-3" class="solution-answer env-green proof solution">
<p><span class="proof-title"><em>Solution 3</em>. </span>&nbsp;</p>
<p><strong>For linear probability model (LPM):</strong></p>
<ul>
<li>African American applicant (<code>afam_binary = 1</code>): <span class="math display">\[
\widehat{deny} = -0.09 + 0.56 \times 0.3 + 0.18 \times 1 = 0.258
\]</span></li>
<li>Non-African American applicant (<code>afam_binary = 0</code>): <span class="math display">\[
\widehat{deny} = -0.09 + 0.56 \times 0.3 + 0.18 \times 0 = 0.078
\]</span></li>
</ul>
<p><strong>For logit model:</strong></p>
<ul>
<li>African American applicant: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.3, afam = 1) = \frac{1}{1 + e^{-(-4.13 + 5.37 \times 0.3 + 1.27 \times 1)}} \approx 0.22
\]</span></li>
<li>Non-African American applicant: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.3, afam = 1) = \frac{1}{1 + e^{-(-4.13 + 5.37 \times 0.3 + 1.27 \times 0)}} \approx 0.07
\]</span></li>
</ul>
<p><strong>For probit model:</strong></p>
<ul>
<li>African American applicant: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.3, afam = 1) = \Phi(-2.26 + 2.74 \times 0.3 + 0.71 \times 1) = \Phi(-0.728)
\]</span> Refer to the standard normal table for <span class="math inline">\(\Phi(-0.728) \approx 0.23\)</span>.</li>
<li>Non-African American applicant: <span class="math display">\[
\widehat{P}(deny = 1 | pirat = 0.3, afam = 0) = \Phi(-2.26 + 2.74 \times 0.3 + 0.71 \times 0) \approx 0.075
\]</span> Refer to the standard normal table for <span class="math inline">\(\Phi(-1.438) \approx 0.075\)</span>.</li>
</ul>
</div>
</section>
</section>
<section id="summary-logit-vs.-probit-vs.-lpm" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="summary-logit-vs.-probit-vs.-lpm"><span class="header-section-number">4</span> Summary: Logit vs.&nbsp;Probit vs.&nbsp;LPM</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Linear</th>
<th>Logit</th>
<th>Probit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Function</strong></td>
<td>Linear</td>
<td>Logistic CDF</td>
<td>Normal CDF</td>
</tr>
<tr class="even">
<td><strong>Predicted probabilities</strong></td>
<td>Can be outside [0,1]</td>
<td>Always in [0,1]</td>
<td>Always in [0,1]</td>
</tr>
<tr class="odd">
<td><strong>Interpretation</strong></td>
<td>Direct (probability)</td>
<td>Log-odds / Odds ratio</td>
<td>Z-score</td>
</tr>
<tr class="even">
<td><strong>Heteroskedasticity</strong></td>
<td>Always present</td>
<td>Accounted for</td>
<td>Accounted for</td>
</tr>
<tr class="odd">
<td><strong>When to use</strong></td>
<td>Quick approximation</td>
<td>Preferred for most applications</td>
<td>Similar to logit; standard in some fields</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>