{
  "hash": "dcc20298a39eaa2ed2a530401fec0636",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Visualization\"\n---\n\n::: {.callout-note appearance=\"simple\" icon=false}\n**Study Objectives**\n\n- Loads and prepares the California school dataset (CASchools) for analysis.\n  - Demonstrates how to visualize data using scatter plots, line charts, histograms, box plots.\n  - Explores expenditure per student across different grade spans.\n  - Investigates correlations between expenditure and other variables.\n- QQ plots to assess normality and interpret skewness and kurtosis in the data.\n  - Given a QQ plot, you should be able to identify how does the distribution compare to normal: positively skewed, negatively skewed, has fat tails, or thin tails.\n:::\n\n## Descriptive Analysis and Data Visualization with `CASchools` {#descriptive-analysis-and-data-visualization-with-caschools}\n\nData visualization is a powerful tool for understanding patterns, relationships, and distributions in datasets. In this session, we will explore the California Schools dataset using various visualization techniques including histograms, box plots, scatter plots, and Q-Q plots. These visualizations help us answer important questions about educational spending, student performance, and the relationships between various school characteristics.\n\n### Dataset Overview\n\nThe following prints the first and last 5 rows of the dataset, together with data types of each column: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages and dataset\npkgs <- c(\"tidyverse\", \"moments\", \"data.table\", \"ggsci\")\nmissing <- setdiff(pkgs, rownames(installed.packages()))\nif (length(missing) > 0) install.packages(missing)\ninvisible(lapply(pkgs, function(pkg) suppressPackageStartupMessages(library(pkg, character.only = TRUE))))\nf_name <- \"https://raw.githubusercontent.com/my1396/FIN5005-Fall2025/refs/heads/main/data/CASchools_test_score.csv\"\ncas <- read_csv(f_name, \n  col_types = cols(\n    county = col_factor(), # read as factor\n    grades = col_factor()\n  ))\n```\n:::\n\n\n\nThe following prints the first and last 5 rows of the dataset, together with data types of each column: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncas %>% as.data.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     district                          school      county grades students\n        <num>                          <char>      <fctr> <fctr>    <num>\n  1:    75119              Sunol Glen Unified     Alameda  KK-08      195\n  2:    61499            Manzanita Elementary       Butte  KK-08      240\n  3:    61549     Thermalito Union Elementary       Butte  KK-08     1550\n  4:    61457 Golden Feather Union Elementary       Butte  KK-08      243\n  5:    61523        Palermo Union Elementary       Butte  KK-08     1335\n ---                                                                     \n416:    68957          Las Lomitas Elementary   San Mateo  KK-08      984\n417:    69518            Los Altos Elementary Santa Clara  KK-08     3724\n418:    72611          Somis Union Elementary     Ventura  KK-08      441\n419:    72744               Plumas Elementary        Yuba  KK-08      101\n420:    72751            Wheatland Elementary        Yuba  KK-08     1778\n     teachers calworks   lunch computer expenditure    income   english  read\n        <num>    <num>   <num>    <num>       <num>     <num>     <num> <num>\n  1:    10.90   0.5102  2.0408       67    6384.911 22.690001  0.000000 691.6\n  2:    11.15  15.4167 47.9167      101    5099.381  9.824000  4.583333 660.5\n  3:    82.90  55.0323 76.3226      169    5501.955  8.978000 30.000002 636.3\n  4:    14.00  36.4754 77.0492       85    7101.831  8.978000  0.000000 651.9\n  5:    71.50  33.1086 78.4270      171    5235.988  9.080333 13.857677 641.8\n ---                                                                         \n416:    59.73   0.1016  3.5569      195    7290.339 28.716999  5.995935 700.9\n417:   208.48   1.0741  1.5038      721    5741.463 41.734108  4.726101 704.0\n418:    20.15   3.5635 37.1938       45    4402.832 23.733000 24.263039 648.3\n419:     5.00  11.8812 59.4059       14    4776.336  9.952000  2.970297 667.9\n420:    93.40   6.9235 47.5712      313    5993.393 12.502000  5.005624 660.5\n      math\n     <num>\n  1: 690.0\n  2: 661.9\n  3: 650.9\n  4: 643.5\n  5: 639.9\n ---      \n416: 707.7\n417: 709.5\n418: 641.7\n419: 676.5\n420: 651.0\n```\n\n\n:::\n:::\n\n\nThe [`cas`](https://www.rdocumentation.org/packages/AER/versions/1.2-15/topics/CASchools) dataset contains information on 420 public school districts in California, specifically those that operate either kindergarten through 6th grade (K–6) or kindergarten through 8th grade (K–8) schools, with data collected for the years 1998 and 1999.\n\nThe dataset includes:\n\n- **Student performance measures** (average reading and math scores).\n- **School characteristics** (such as enrollment, number of teachers, student–teacher ratio, number of computers, expenditure per student).\n- **Student demographics** (including income, percentage qualifying for reduced-price lunch, percentage of English learners, etc.).\n\n`cas` is a data frame containing 420 observations on 14 variables. Refer to the following table for the full definition.\n\n| Variable      | Description                                                  |\n| ------------- | ------------------------------------------------------------ |\n| `district`    | Character. District code. Unique ID.                         |\n| `school`      | Character. School name.                                      |\n| `county`      | Factor indicating county.                                    |\n| `grades`      | Factor indicating grade span covered by the district’s schools. <br />It takes on two values: <br />- `KK-06`: means the district’s schools serve kindergarten through 6th grade.<br />- `KK-08`: means the district’s schools serve kindergarten through 6th grade. |\n| `students`    | Total enrollment.                                            |\n| `teachers`    | Number of teachers.                                          |\n| `calworks`    | Percent qualifying for CalWorks (income assistance program). |\n| `lunch`       | Percent qualifying for reduced-price lunch.                  |\n| `computer`    | Number of computers.                                         |\n| `expenditure` | Expenditure per student.                                     |\n| `income`      | District average income (in USD 1,000).                      |\n| `english`     | Percent of English learners <br />(i.e., students for whom English is a second language). |\n| `read`        | Average reading score.                                       |\n| `math`        | Average math score.                                          |\n\nData source: Stock, J. H. and Watson, M. W. (2020). [Introduction to Econometrics](https://www.sea-stat.com/wp-content/uploads/2020/08/James-H.-Stock-Mark-W.-Watson-Introduction-to-Econometrics-Global-Edition-Pearson-Education-Limited-2020.pdf), 4th ed. Pearson.\n\n--------------------------------------------------------------------------------\n\n### Summary Statistics\n\nThe following displays the summary for each variable in the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(cas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    district        school                  county      grades   \n Min.   :61382   Length:420         Sonoma     : 29   KK-08:359  \n 1st Qu.:64308   Class :character   Kern       : 27   KK-06: 61  \n Median :67760   Mode  :character   Los Angeles: 27              \n Mean   :67473                      Tulare     : 24              \n 3rd Qu.:70419                      San Diego  : 21              \n Max.   :75440                      Santa Clara: 20              \n                                    (Other)    :272              \n    students          teachers          calworks          lunch       \n Min.   :   81.0   Min.   :   4.85   Min.   : 0.000   Min.   :  0.00  \n 1st Qu.:  379.0   1st Qu.:  19.66   1st Qu.: 4.395   1st Qu.: 23.28  \n Median :  950.5   Median :  48.56   Median :10.520   Median : 41.75  \n Mean   : 2628.8   Mean   : 129.07   Mean   :13.246   Mean   : 44.71  \n 3rd Qu.: 3008.0   3rd Qu.: 146.35   3rd Qu.:18.981   3rd Qu.: 66.86  \n Max.   :27176.0   Max.   :1429.00   Max.   :78.994   Max.   :100.00  \n                                                                      \n    computer       expenditure       income          english      \n Min.   :   0.0   Min.   :3926   Min.   : 5.335   Min.   : 0.000  \n 1st Qu.:  46.0   1st Qu.:4906   1st Qu.:10.639   1st Qu.: 1.941  \n Median : 117.5   Median :5215   Median :13.728   Median : 8.778  \n Mean   : 303.4   Mean   :5312   Mean   :15.317   Mean   :15.768  \n 3rd Qu.: 375.2   3rd Qu.:5601   3rd Qu.:17.629   3rd Qu.:22.970  \n Max.   :3324.0   Max.   :7712   Max.   :55.328   Max.   :85.540  \n                                                                  \n      read            math      \n Min.   :604.5   Min.   :605.4  \n 1st Qu.:640.4   1st Qu.:639.4  \n Median :655.8   Median :652.4  \n Mean   :655.0   Mean   :653.3  \n 3rd Qu.:668.7   3rd Qu.:665.8  \n Max.   :704.0   Max.   :709.5  \n                                \n```\n\n\n:::\n:::\n\n\n**Interpreting the Summary Statistics**\n\nThis summary provides key insights into our dataset:\n\n- **Continuous variables** (students, teachers, expenditure, income, etc.) show their distribution through quartiles, mean, and range\n- **Categorical variables** (county, grades) show frequency counts\n- Notice the **range of expenditure** per student: from around \\\\$3,900 to over \\\\$7,700 - this substantial variation will be a key focus of our analysis\n- **Test scores** (reading and math) also show considerable variation, suggesting potential relationships with school resources\n\n### Expenditure Variation Analysis\n\nQ: To what extent does expenditure per student vary?  \n\nUnderstanding the distribution of expenditure per student is crucial for education policy analysis. Let's examine detailed descriptive statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquick_summary <- function(x, full=FALSE) {\n    # Function to compute basic descriptive statistics\n    if (!full){\n        # Basic summary\n        data.frame(\n          n = length(x),\n          min = min(x),\n          mean = mean(x),\n          median = median(x),\n          max = max(x),\n          sd = sd(x),\n          skewness = moments::skewness(x),\n          kurtosis = moments::kurtosis(x),\n          row.names = NULL\n        )\n    } else {\n        # Full summary with quartiles and IQR\n        data.frame(\n          n = length(x),\n          min = min(x),\n          Q1 = quantile(x, 0.25),\n          mean = mean(x),\n          median = median(x),\n          Q3 = quantile(x, 0.75),\n          max = max(x),\n          IQR = IQR(x),\n          sd = sd(x),\n          skewness = moments::skewness(x),\n          kurtosis = moments::kurtosis(x),\n          row.names = NULL\n        )\n    }\n}\nquick_summary(cas$expenditure) %>% round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n     min    mean  median     max     sd skewness kurtosis\n1 420 3926.07 5312.41 5214.52 7711.51 633.94     1.07     4.88\n```\n\n\n:::\n:::\n\n\n**Interpreting the Results:**\n\n- **Range:** Expenditure varies from about \\\\$3,926 to \\\\$7,712 per student - a difference of nearly \\\\$4,000\n- **Central Tendency:** The mean (\\\\$5,312) is slightly higher than the median (\\\\$5,196), **suggesting a slight right skew**\n- **Variability:** Standard deviation of \\\\$633 indicates moderate spread around the mean\n- **Skewness (1.07):** Positive skewness confirms some districts spend considerably more than average\n- **Kurtosis (4.88):** Larger than 3 indicates a distribution with fat tails relative to the normal distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic histogram\nggplot(cas, aes(x = expenditure)) +\n  geom_histogram(binwidth = 500, boundary = 0, fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Histogram of Expenditure per Student\",\n       x = \"Expenditure per Student (USD)\",\n       y = \"Frequency\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n:::\n\n\n**What the Histogram Reveals:**\n\n- Most districts cluster around the \\\\$5,000-\\\\$5,500 range\n- Variability is moderate\n- The distribution has a long right tail, indicating positive skewness. That suggests that expenditure per student is concentrated at lower values for most districts, while a smaller number of districts spend substantially more, pulling the mean above the median\n- There are **few extreme positive outliers**, indicating some districts do spend significantly more than average\n\n\n--------------------------------------------------------------------------------\n\n### Group Comparison: K-6 vs K-8 Schools\n\nQ: Are there any differences in expenditure per student between K-6 and K-8 schools?\n\nThis comparison helps us understand whether grade span affects resource allocation. Let's examine the statistics for each group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncas %>%\n    group_by(grades) %>%\n    group_map(~ {\n        s <- quick_summary(.x$expenditure, full=TRUE)\n        s <- cbind(\n            grades = .y$grades,    # add group info\n            s)\n        return(s)\n    }) %>%\n    bind_rows()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  grades   n      min       Q1     mean   median       Q3      max      IQR\n1  KK-08 359 3926.070 4881.139 5267.365 5195.919 5539.380 7711.507 658.2412\n2  KK-06  61 4715.446 5092.917 5577.493 5399.383 5990.794 7614.379 897.8770\n        sd skewness kurtosis\n1 618.6415 1.094514 5.284716\n2 662.8033 1.019435 3.309185\n```\n\n\n:::\n:::\n\n\n**Key Findings:**\n\n- **K–6 schools** (61 districts): Mean expenditure of \\\\$5,577, slightly higher than K–8 schools\n- **K–8 schools** (359 districts): Mean expenditure of \\\\$5,267, with a larger sample size\n- K–6 schools indicating higher variability, with a standard deviation of \\\\$662 compared to \\\\$618 for K-8 schools\n- **Skewness** is positive for both groups, with K--8 schools showing slightly more skewness\n- The difference suggests that **smaller grade span districts may have slightly higher per-pupil spending**\n\n\n#### Box plot by grades span\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cas, aes(x = grades, y = expenditure, fill = grades)) +\n  geom_boxplot() +\n  scale_fill_npg() +\n  labs(x = \"Grade Span\",\n       y = \"Expenditure per Student (USD)\") +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/hist-1.png){width=50%}\n:::\n:::\n\n\n**Understanding the Box Plot:**\n\n1. **Box and middle bar (median)**\n\n   -   The **box** itself spans from the **first quartile (Q1, 25th percentile)** to the **third quartile (Q3, 75th percentile)**.\n\n   -   This range is called the **interquartile range (IQR = Q3 - Q1)**.\n\n   -   The **middle bar** inside the box represents the **median (50th percentile)**.\n\n       -   If the median is closer to the bottom of the box, the lower half of the data is more concentrated.\n\n       -   If closer to the top, the upper half is more concentrated. \n\n2. **Whiskers**\n\n   -   The **whiskers** extend from the box to show the range of the data **excluding outliers**.\n\n   -   A whisker extends to the **largest/smallest value within 1.5 × IQR from the box**:\n\n       -   Upper whisker = largest value ≤ Q3 + 1.5 × IQR\n\n       -   Lower whisker = smallest value ≥ Q1 - 1.5 × IQR\n\n3. **Outliers**\n\n   -   **Points beyond the whiskers** are plotted individually as **outliers**.\n\n   -   These are values that are unusually high or low relative to the bulk of the data.\n\n::: {.callout-tip appearance=\"simple\"}\n**Summary of boxplot**\n\n- Box: middle 50% of the data\n- Middle line: median\n- Whiskers: typical range, excluding extreme values\n- Outliers: extreme observations\n:::\n\n--------------------------------------------------------------------------------\n\n**Interpreting the Box Plot:**\n\n- **Median lines:** K--6 districts show a higher median expenditure than K-8 districts\n- **Box sizes:** K--6 district show a larger interquartile ranges (IQR), indicating greater middle 50% spread\n- **Outliers:** K--8 groups show more positive outliers (points beyond the whiskers), representing districts with unusually high expenditure\n\n\n\n--------------------------------------------------------------------------------\n\n### Correlation Analysis\n\n**Q: What predicts expenditure per student?**\n\nUnderstanding which factors correlate with expenditure helps identify patterns in educational resource allocation. Let's examine correlations:\n\nCorrelation coefficients in ascending order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the set of numeric variables\nv <- setdiff(\n    names(cas),\n    c(\"district\", \"school\", \"county\", \"grades\")\n)\ncorExp <- cor(cas[\"expenditure\"], cas[setdiff(v, \"expenditure\")])\nt(corExp) %>%\n    as.data.frame() %>%\n    rownames_to_column(var = \"variable\") %>%\n    rename(correlation = expenditure) %>% \n    arrange(correlation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variable correlation\n1 students -0.11228455\n2 teachers -0.09519483\n3  english -0.07139604\n4 computer -0.07131050\n5    lunch -0.06103871\n6 calworks  0.06788857\n7     math  0.15498949\n8     read  0.21792682\n9   income  0.31448448\n```\n\n\n:::\n:::\n\n\n**Key Correlation Insights:**\n\n- No strong correlations (e.g., $>|0.7|$) with expenditure\n- **Positive correlations:** Income (0.31), math scores (0.22), and reading scores (0.15)\n- **Moderate Negative correlations:** Students($-0.11$), indicating districts with a larger amount of students tend to spend less per student\n- **Interpretation:** \n  - Wealthier districts tend to spend more per student\n  - Higher spending correlates with better test scores\n  - Districts with more students may face budget constraints leading to lower per-student expenditure\n\n\n\nPlot scatter plots for the top three correlated variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_vars <- c(\"income\", \"math\", \"read\")\ncas_long <- cas %>%\n    select(expenditure, all_of(top_vars)) %>%\n    pivot_longer(cols = all_of(top_vars), names_to = \"variable\", values_to = \"value\")\nggplot(cas_long, aes(x = value, y = expenditure)) +\n    geom_point(alpha = 0.6, color = \"#1976d2\") +\n    facet_wrap(~variable, scales = \"free_x\") +\n    labs(\n        title = \"Scatter Plots of Expenditure per Student vs. Top Correlated Variables\",\n        x = \"Value\",\n        y = \"Expenditure per Student (USD)\"\n    ) +\n    theme_minimal(base_size = 14)   \n```\n\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-7-1.png){width=1152}\n:::\n:::\n\n\n**What These Scatter Plots Reveal:**\n\n- **Income vs. Expenditure:** Positive relationship - wealthier districts consistently spend more per student; the trend is relatively clear with some variability;\n- **Math Scores vs. Expenditure:** Positive trend suggests higher spending correlates with better math performance; the points are more scattered, indicating other factors also play a role;\n- **Reading Scores vs. Expenditure:** Similar pattern to math scores, showing the relationship between resources and achievement\n- **Data Distribution:** Points are fairly scattered, indicating that while correlations exist, other factors also influence these relationships\n\n\n--------------------------------------------------------------------------------\n\n### Academic Performance Relationship {#academic-performance-relationship}\n\nQ: what is the relationship between district level maths and reading scores?\n\nAcademic performance across different subjects often correlates, as they reflect overall educational quality and student preparation. Let's examine this relationship:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(cas, cor.test(math, read))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  math and read\nt = 49.005, df = 418, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9073417 0.9359362\nsample estimates:\n      cor \n0.9229015 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cas, aes(x = read, y = math)) +\n    geom_point(alpha = 0.6, color = \"#1976d2\") +\n    geom_smooth(method = \"lm\", color = \"#d32f2f\") +\n    labs(\n        title = \"Scatter Plot of Math vs. Reading Scores\",\n        x = \"Average Reading Score\",\n        y = \"Average Math Score\"\n    ) +\n    theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-9-1.png){width=576}\n:::\n:::\n\n\n**Analysis of the Relationship:**\n\n- **Strong positive correlation:** Districts with higher reading scores typically have higher math scores\n- **Linear trend:** The smooth line shows a clear linear relationship between the two subjects\n- **Tight clustering:** Most points cluster closely around the trend line, indicating a strong relationship\n- **Educational insights:** \n  - This suggests that factors affecting academic performance impact multiple subjects similarly\n  - Districts that excel in one area tend to excel in others\n\n\n--------------------------------------------------------------------------------\n\n## Q-Q Plot\n\nThe <span class=\"env-green\">Q-Q plot</span>, or <span class=\"env-green\">quantile-quantile plot</span>, is a graphical tool to help us assess if a set of data plausibly came from some theoretical distribution such as a normal distribution. \n\n**Understanding Q-Q Plots:**\n\nA QQ plot is a scatter plot created by plotting two sets of quantiles against one another. \n\n- If both sets of quantiles came from the same distribution, we should see the points forming a line that's roughly straight. \n\n- For example, if we run a statistical analysis that assumes our **residuals** are normally distributed, we can use a <span class=\"env-green\">normal QQ plot</span> to check that assumption. \n  \n  When the theoretical quantiles are from a normal distribution, the plot is called a **normal QQ plot**.\n\n**Why Q-Q Plots Matter:**\n\n- Many statistical tests assume normality; deviations from normality can affect the validity of statistical inferences\n- Q-Q plots provide a visual method to assess these assumptions\n- They help identify the type of non-normality (skewness, heavy tails, etc.)\n\n\n### QQ plot visualization tool \n\n<https://xiongge.shinyapps.io/QQplots/>\n\n- Adjust Skewness and Kurtosis to see how the QQ plot changes.\n- Note the website is not able to host many users at the same time, so if it does not load, please try again later.\n\n--------------------------------------------------------------------------------\n\n### Skewness\n\n#### Positive skew\n\nPositively skewed (mean > median) data have a J-shaped pattern in the Q-Q plot.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nSummary statistics:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n      n   min  mean median  max   sd skewness kurtosis\n1 10000 -1.92 -0.01  -0.19 5.41 0.99     0.86     3.57\n```\n\n\n:::\n:::\n\n\n💡 Note that for a positive skewed distribution, **the mean is larger than the median** because the long right tail pulls the mean above the median.\n\n**Understanding Positive Skewness:**\n\n- **Shape:** Long tail extending to the right\n- **Mean vs. Median:** Mean > Median (tail pulls the mean upward)\n- **Q-Q Plot Pattern:** J-shaped curve, points above the line at both ends\n- **Real-world examples:** Income distribution, housing prices\n- **Statistical implications:** May indicate floor effects or bounded distributions\n\n\n#### Negative skew\n\nNegatively skewed (mean < median) data have Q-Q plots that display an inverted J-shape.\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nSummary statistics:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n      n   min mean median max   sd skewness kurtosis\n1 10000 -4.87    0   0.19   2 0.98    -0.85     3.55\n```\n\n\n:::\n:::\n\n\n💡 Note that for a negatively skewed distribution, **the mean is smaller than the median** because the long left tail pulls the mean above the median.\n\n**Understanding Negative Skewness:**\n\n- **Shape:** Long tail extending to the left\n- **Mean vs. Median:** Mean < Median (tail pulls the mean downward)\n- **Q-Q Plot Pattern:** Inverted J-shaped curve, points below the line at both ends\n- **Real-world examples:** \n  - **Test scores (when most students perform well):** Most students score high (80-100), with fewer low scores creating a left tail\n  - **Age at retirement:** Most people retire around 65-67, but some retire much earlier due to health or financial reasons\n- **Statistical implications:** May indicate ceiling effects or bounded distributions\n\n### Kurtosis\n\nKurtosis measures the \"tailedness\" of a distribution compared to a normal distribution. Understanding kurtosis helps identify distributions with unusually many or few extreme values.\n\n#### Fat tails\n\nThis plot shows a t-distribution with $3$ degrees of freedom, which has heavier tails than a normal distribution.\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nSummary statistics:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     n   min  mean median  max   sd skewness kurtosis\n1 1000 -8.27 -0.01      0 8.74 1.63     0.21     7.54\n```\n\n\n:::\n:::\n\n\n**Understanding Fat Tails (High Kurtosis):**\n\n- **Q-Q Plot Pattern:** Reverse S-shaped curve - points below the line at low quantiles, above at high quantiles.\n- **Kurtosis > 3:** Indicates heavier tails than normal distribution\n- **Practical meaning:** More extreme values (both high and low) occur than expected under normality\n- **Real-world examples:** \n  - **Financial returns:** Stock market crashes and booms occur more frequently than normal distribution predicts\n  - **Measurement errors:** Occasionally very large errors occur due to equipment malfunction or human mistakes\n  - **Response times:** Most responses are quick, but some take much longer due to system overload or user distraction\n- **Statistical implications:** Higher risk of extreme events; standard confidence intervals may be too narrow\n\n#### Thin tails\n\nThis example shows a distribution with lighter tails than normal.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Data_Visualization_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\nSummary statistics:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     n   min mean median  max   sd skewness kurtosis\n1 1000 -1.18 0.01   0.01 1.17 0.59    -0.03     1.87\n```\n\n\n:::\n:::\n\n\n**Understanding Thin Tails (Low Kurtosis):**\n\n- **Q-Q Plot Pattern:** S-shaped curve - points above the line at low quantiles, below at high quantilees.\n- **Kurtosis < 3:** Indicates lighter tails than normal distribution\n- **Practical meaning:** Fewer extreme values occur than expected under normality\n- **Real-world examples:** Bounded measurements, standardized test scores, some quality control data\n- **Statistical implications:** Lower risk of extreme events; data more predictable than normal assumption suggests\n\n--------------------------------------------------------------------------------\n\n**Summary of Distribution Shapes**\n\nUnderstanding these patterns helps in:\n\n- **Choosing appropriate statistical methods**\n- **Identifying data quality issues**\n- **Making informed assumptions about uncertainty**\n- **Selecting proper transformations when needed**\n- **Interpreting results correctly in context**",
    "supporting": [
      "02_Data_Visualization_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}